My Application: Application Class Reference
Application Class Reference
#include <Application.h>
Public Member Functions
Application ()
~Application ()
void Init ()
void Run ()
void Exit ()
Static Public Member Functions
static bool IsKeyPressed (unsigned short key)
Data Fields
float height
float width
Private Attributes
StopWatch m_timer
Detailed Description
Definition at line 7 of file Application.h.
Constructor & Destructor Documentation
Application::Application ()
Definition at line 46 of file Application.cpp.
Application::~Application ()
Definition at line 50 of file Application.cpp.
Member Function Documentation
void Application::Exit ()
Definition at line 182 of file Application.cpp.
References m_window.
Referenced by main().
void Application::Init ()
Definition at line 60 of file Application.cpp.
References error_callback(), SharedData::GetInstance(), height, SharedData::height, m_window, resize_callback(), width, and SharedData::width.
Referenced by main().
bool Application::IsKeyPressed (unsigned short key) static
Definition at line 41 of file Application.cpp.
Referenced by SP2::Character_Movement(), Scene2::Character_Movement(), Scene3::Character_Movement(), NPC::Door(), SceneMenu::mouseControl(), Run(), NPC::Scene1(), NPC::Shop(), Shop::ShopOptions(), Camera::Update(), Camera3::Update(), SceneWin::Update(), Shop::Update(), SP2::Update(), Scene2::Update(), Scene3::Update(), SceneMenu::UpdateMenu(), SceneMenu::userInput(), and Shop::userInput().
void Application::Run ()
Definition at line 115 of file Application.cpp.
References SharedData::CUTSCENE, Scene::Exit(), frameTime, SharedData::G_CUTSCENE, SharedData::GAME, StopWatch::getElapsedTime(), SharedData::GetInstance(), Scene::Init(), IsKeyPressed(), m_timer, m_window, SharedData::MENU, SharedData::QUIT, Scene::Render(), SharedData::SCENE2, SharedData::SCENE3, SharedData::SHOP, StopWatch::startTimer(), SharedData::stateCheck, Scene::Update(), StopWatch::waitUntil(), and SharedData::WIN.
Referenced by main().
Field Documentation
float Application::height
Definition at line 16 of file Application.h.
Referenced by Init().
StopWatch Application::m_timer private
Definition at line 21 of file Application.h.
Referenced by Run().
float Application::width
Definition at line 17 of file Application.h.
Referenced by Init().
The documentation for this class was generated from the following files:
MyGraphics/Source/Application.h
MyGraphics/Source/Application.cpp