My Application: Mouse Class Reference
Mouse Class Reference
Defines a player's mouse attribute and its methods.
#include <Mouse.h>
Public Member Functions
Mouse ()
Mouse() is a constructor for Mouse class, where I set the default values needed for the methods.
~Mouse ()
~Mouse() is a destructor for Mouse class.
void AssignePointToVector (POINT point, Vector3 &vec)
AssignePointToVector(POINT point, Vector3 &vec), is a convertor function for Mouse class, where I convert the POINT values into a vector value.
void MouseUpdate (double dt, Camera3 &camera)
MouseUpdate(double dt, Camera3 &camera) is a overloaded update function for Mouse class, where I update the position values for the mouse cursor.
void MouseUpdate (double dt, Camera3 &camera, float &followx, float &followy)
MouseUpdate(double dt, Camera3 &camera, float& followx, float& followy) is a update function for Mouse class, where I update the position values for the mouse cursor.
void Callback ()
Data Fields
int mouseSensitivity
int resetX
int resetY
LONG boundaryCheckX
LONG boundaryCheckY
Vector3 pos
vector< Vector3 > position_Vector
Detailed Description
Defines a player's mouse attribute and its methods.
Class Dweller:
Definition at line 30 of file Mouse.h.
Constructor & Destructor Documentation
Mouse::Mouse ()
Mouse() is a constructor for Mouse class, where I set the default values needed for the methods.
Definition at line 24 of file Mouse.cpp.
References boundaryCheckX, boundaryCheckY, resetX, and resetY.
Mouse::~Mouse ()
~Mouse() is a destructor for Mouse class.
Definition at line 42 of file Mouse.cpp.
Member Function Documentation
void Mouse::AssignePointToVector (POINT point, Vector3 & vec)
AssignePointToVector(POINT point, Vector3 &vec), is a convertor function for Mouse class, where I convert the POINT values into a vector value.
Parameters
point A Point values that need to be convert to Vector3.
vec A Vector3 that stores the point value after converting
Definition at line 64 of file Mouse.cpp.
References Vector3::x, and Vector3::y.
Referenced by MouseUpdate().
void Mouse::Callback ()
void Mouse::MouseUpdate (double dt, Camera3 & camera)
MouseUpdate(double dt, Camera3 &camera) is a overloaded update function for Mouse class, where I update the position values for the mouse cursor.
Parameters
dt A double dt that represent the delta time in update.
camera A camera class for the update, to update the camera rotation according to the mouse position movement.
Definition at line 165 of file Mouse.cpp.
References AssignePointToVector(), boundaryCheckX, boundaryCheckY, Camera3::cameraRotate, mouseSensitivity, pos, position_Vector, resetX, resetY, Vector3::x, and Vector3::y.
Referenced by Shop::Update(), Scene3::Update(), SP2::Update(), and Scene2::Update().
void Mouse::MouseUpdate (double dt, Camera3 & camera, float & followx, float & followy)
MouseUpdate(double dt, Camera3 &camera, float& followx, float& followy) is a update function for Mouse class, where I update the position values for the mouse cursor.
Parameters
dt A double dt that represent the delta time in update.
camera A camera class for the update, to update the camera rotation according to the mouse position movement.
followx A float that represent the weapon's position x on screen where the player holds it.
followy A float that represent the weapon's position y on screen where the player holds it.
Definition at line 95 of file Mouse.cpp.
References AssignePointToVector(), boundaryCheckX, boundaryCheckY, Camera3::cameraRotate, mouseSensitivity, pos, position_Vector, resetX, resetY, Vector3::x, and Vector3::y.
Field Documentation
LONG Mouse::boundaryCheckX
Definition at line 36 of file Mouse.h.
Referenced by Mouse(), and MouseUpdate().
LONG Mouse::boundaryCheckY
Definition at line 37 of file Mouse.h.
Referenced by Mouse(), and MouseUpdate().
int Mouse::mouseSensitivity
Definition at line 34 of file Mouse.h.
Referenced by MouseUpdate().
Vector3 Mouse::pos
Definition at line 38 of file Mouse.h.
Referenced by MouseUpdate().
vector<Vector3> Mouse::position_Vector
Definition at line 39 of file Mouse.h.
Referenced by MouseUpdate().
int Mouse::resetX
Definition at line 35 of file Mouse.h.
Referenced by Mouse(), and MouseUpdate().
int Mouse::resetY
Definition at line 35 of file Mouse.h.
Referenced by Mouse(), and MouseUpdate().
The documentation for this class was generated from the following files:
MyGraphics/Source/Mouse.h
MyGraphics/Source/Mouse.cpp