My Application: SP2 Class Reference
SP2 Class Reference
#include <SP2.h>
Public Member Functions
SP2 ()
~SP2 ()
virtual void Init ()
virtual void Update (double dt)
virtual void Render ()
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
char Map [20][20]
float Size = 15
float Z_Displacement = 0
float X_Displacement = -100
Private Types
enum GEOMETRY_TYPE {
GEO_REF_AXES = 0, GEO_REF_QUAD, GEO_LIGHTBALL, GEO_QUAD,
GEO_BB8HEAD, GEO_BB8BODY, GEO_CROSSHAIR, GEO_AMMOICON,
GEO_GOLDICON, GEO_EGGICON, GEO_BOMBICON, GEO_OREICON,
GEO_GUNICON, GEO_SWORDICON, GEO_PICKAXEICON, GEO_LEFT1,
GEO_RIGHT1, GEO_TOP1, GEO_BOTTOM1, GEO_FRONT1,
GEO_BACK1, GEO_STAR, GEO_STORY1, GEO_TEXT,
GEO_PATH, GEO_VENDING, GEO_BAG, GEO_COKE,
GEO_ROBOTB, GEO_ROBOTH, GEO_ROBOT, GEO_ROBOT1,
GEO_ROBOT2, GEO_MOONBALL, GEO_PYRAMIDNEW, GEO_PYRAMIDWALL,
GEO_PYRAMIDPILLAR, GEO_SPACESHIP, GEO_PLANEBODY, GEO_PLANEWING,
GEO_PLANEROCKET, GEO_PYRAMIDFLOOR, GEO_PYRAMIDDOOR, GEO_BULLET,
GEO_PICKAXE, GEO_GUN, GEO_SWORD, GEO_RMSMALL,
GEO_RMMEDIUM, GEO_RMBIG, GEO_EXPLOSION, GEO_EXPLOSION2,
GEO_BULLETSKIN, GEO_BOMB, GEO_CCTV, GEO_EGG,
GEO_POTATO, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1ENABLED, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION,
U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION,
U_LIGHT2_COLOR, U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL,
U_LIGHT2_KQ, U_LIGHT2ENABLED, U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION,
U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT3_POSITION,
U_LIGHT3_COLOR, U_LIGHT3_POWER, U_LIGHT3_KC, U_LIGHT3_KL,
U_LIGHT3_KQ, U_LIGHT3ENABLED, U_LIGHT3_TYPE, U_LIGHT3_SPOTDIRECTION,
U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
enum Items { None = -1, SPACEWING, SPACEROCKET, Num_Object }
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
void UpdateMenu ()
void RenderSkybox ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
void RenderQuadOnScreen (Mesh *mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z)
Renders obj and quads on screen.
void Dialogue (string filename)
float checkNear (Camera3 camera, Vector3 rhs)
void Enemy_Rendering ()
void Enemy_Updating (float dt)
void ObjectsHolding (Mesh *mesh, float size)
void EquipmentHolding (Mesh *mesh, float size)
void RenderObjects (Mesh *mesh, float size, float x, float y, float z)
void Map_Reading ()
void Map_Rendering ()
void Character_Movement (float dt)
Private Attributes
unsigned m_vertexArrayID
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
NPC npc
int parts = 0
int gun
int pickaxe
int sword
Mesh * meshList [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
float LSPEED = 10.f
float moveSkyBoxZ = 91.f
float moveSkyBoxX = 0.f
float potatoRotate
Light light [8]
string new_line
Camera3 camera
Sound sound
vector< string > my_arr
vector< Bullet * > bullet_arr
Vector3 RobotPosition1
double b_coolDown
double b_coolDownLimit
bool startCoolDdown
int b_Ammo
float storyPosition
bool storyDismiss
bool storyShow
string story
float deltaTime
Bullet bullet
Objects objects
int x
int y
int w_x
int w_y
bool robot1moved = false
bool robot1rotate = false
float robot1rotation = 0
Enemy enemy [5]
float throwingdown = 0
float throwingforward = 0
float throwup = 0
Vector3 newcameraposition = (0, 0, 0)
Vector3 oldcameraposition = (0, 0, 0)
bool throwbomb = false
bool thrown = false
bool toggle = false
bool cam1 = false
bool movement = true
bool holdingcctv = false
bool pickupwing = false
bool pickuprocket = false
float followx = 0
float followy = 0
bool fixwing = false
bool fixrocket = false
float coolDownTime
string shop
Objects object [Num_Object]
Objects object_on_hand
int T_object_Num
float JumpTime
float PressTime
Mouse mouse
CollisionDetector detectCollision
Animation animation
float swordRotation
float pickAxeRotation
float gunRotation
float gunTranslation
float swordTranslation
float pickAxeTranslation
bool playSlashingAnimation
bool playShootingAnimation
bool playMiningAnimation
bool playExplosionAnimation
bool usingSword
bool usingGun
bool usingPickAxe
int weaponChoice
rawMaterial oreMaterial_arr [3]
double rm_coolDown
double rm_coolDownLimit
bool startRMcoolDown
float explosionScale
Vector3 explosionLoc
float explosionLocRotateY
float explosionLocRotateX
Detailed Description
Definition at line 37 of file SP2.h.
Member Enumeration Documentation
enum SP2::GEOMETRY_TYPE private
Enumerator
GEO_REF_AXES
GEO_REF_QUAD
GEO_LIGHTBALL
GEO_QUAD
GEO_BB8HEAD
GEO_BB8BODY
GEO_CROSSHAIR
GEO_AMMOICON
GEO_GOLDICON
GEO_EGGICON
GEO_BOMBICON
GEO_OREICON
GEO_GUNICON
GEO_SWORDICON
GEO_PICKAXEICON
GEO_LEFT1
GEO_RIGHT1
GEO_TOP1
GEO_BOTTOM1
GEO_FRONT1
GEO_BACK1
GEO_STAR
GEO_STORY1
GEO_TEXT
GEO_PATH
GEO_VENDING
GEO_BAG
GEO_COKE
GEO_ROBOTB
GEO_ROBOTH
GEO_ROBOT
GEO_ROBOT1
GEO_ROBOT2
GEO_MOONBALL
GEO_PYRAMIDNEW
GEO_PYRAMIDWALL
GEO_PYRAMIDPILLAR
GEO_SPACESHIP
GEO_PLANEBODY
GEO_PLANEWING
GEO_PLANEROCKET
GEO_PYRAMIDFLOOR
GEO_PYRAMIDDOOR
GEO_BULLET
GEO_PICKAXE
GEO_GUN
GEO_SWORD
GEO_RMSMALL
GEO_RMMEDIUM
GEO_RMBIG
GEO_EXPLOSION
GEO_EXPLOSION2
GEO_BULLETSKIN
GEO_BOMB
GEO_CCTV
GEO_EGG
GEO_POTATO
NUM_GEOMETRY
Definition at line 39 of file SP2.h.
enum SP2::Items private
Enumerator
None
SPACEWING
SPACEROCKET
Num_Object
Definition at line 183 of file SP2.h.
enum SP2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1ENABLED
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2ENABLED
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_LIGHT3_POSITION
U_LIGHT3_COLOR
U_LIGHT3_POWER
U_LIGHT3_KC
U_LIGHT3_KL
U_LIGHT3_KQ
U_LIGHT3ENABLED
U_LIGHT3_TYPE
U_LIGHT3_SPOTDIRECTION
U_LIGHT3_COSCUTOFF
U_LIGHT3_COSINNER
U_LIGHT3_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 113 of file SP2.h.
Constructor & Destructor Documentation
SP2::SP2 ()
Definition at line 20 of file SP2.cpp.
SP2::~SP2 ()
Definition at line 23 of file SP2.cpp.
Member Function Documentation
void SP2::Character_Movement (float dt) private
Definition at line 1577 of file SP2.cpp.
References camera, Camera3::cameraRotate, Camera3::cameraSpeed, checkNear(), NPC::DOT::Collision, Vector3::Cross(), Camera3::defaultUp, Math::DegreeToRadian(), NPC::door, enemy, followx, followy, Application::IsKeyPressed(), light, m_parameters, Map, Camera3::maxCameraX, Camera3::maxX, Camera3::maxZ, Camera3::minX, Camera3::minZ, movement, npc, NPC::DOT::Nposition, Camera::position, Light::position, Light::power, Camera3::Reset(), Size, Camera::target, U_LIGHT3_POWER, Camera::up, Camera3::view, VtoP(), Vector3::x, X_Displacement, Vector3::y, Vector3::z, and Z_Displacement.
Referenced by Update().
float SP2::checkNear (Camera3 camera, Vector3 rhs) private
Definition at line 414 of file SP2.cpp.
References Camera::position, Vector3::x, and Vector3::z.
Referenced by Character_Movement().
void SP2::Dialogue (string filename) private
Definition at line 815 of file SP2.cpp.
References my_arr, and new_line.
Referenced by Init().
void SP2::Enemy_Rendering () private
Definition at line 1505 of file SP2.cpp.
References enemy, GEO_COKE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), Enemy::Return_Position(), MS::Scale(), MS::Translate(), Position::x, and Position::z.
Referenced by Render().
void SP2::Enemy_Updating (float dt) private
Definition at line 1496 of file SP2.cpp.
References camera, enemy, Enemy::enemy_attack(), Enemy::Enemy_movement(), Map, Camera::position, Size, VtoP(), Vector3::x, X_Displacement, Vector3::y, Vector3::z, and Z_Displacement.
Referenced by Update().
void SP2::EquipmentHolding (Mesh * mesh, float size) private
Definition at line 1478 of file SP2.cpp.
References camera, followx, followy, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
void SP2::Exit () virtual
Implements Scene.
Definition at line 1491 of file SP2.cpp.
References m_programID, and m_vertexArrayID.
void SP2::Init () virtual
Implements Scene.
Definition at line 26 of file SP2.cpp.
References b_coolDown, b_coolDownLimit, camera, Camera3::cameraRotate, NPC::DOT::canGoThrough, NPC::DOT::Collision, Light::color, Light::cosCutOff, Light::cosInner, Math::DegreeToRadian(), Dialogue(), NPC::door, explosionLoc, explosionLocRotateX, explosionLocRotateY, explosionScale, Light::exponent, MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRepeatQuad(), MeshBuilder::GenerateText(), GEO_AMMOICON, GEO_BACK1, GEO_BB8BODY, GEO_BB8HEAD, GEO_BOMB, GEO_BOMBICON, GEO_BOTTOM1, GEO_BULLETSKIN, GEO_CCTV, GEO_COKE, GEO_CROSSHAIR, GEO_EGGICON, GEO_EXPLOSION, GEO_EXPLOSION2, GEO_FRONT1, GEO_GOLDICON, GEO_GUN, GEO_GUNICON, GEO_LEFT1, GEO_MOONBALL, GEO_OREICON, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_POTATO, GEO_PYRAMIDDOOR, GEO_PYRAMIDFLOOR, GEO_PYRAMIDNEW, GEO_PYRAMIDPILLAR, GEO_PYRAMIDWALL, GEO_QUAD, GEO_RIGHT1, GEO_RMBIG, GEO_RMMEDIUM, GEO_RMSMALL, GEO_ROBOT, GEO_ROBOT1, GEO_ROBOTB, GEO_ROBOTH, GEO_SPACESHIP, GEO_STORY1, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, GEO_TOP1, gun, gunRotation, gunTranslation, Camera3::Init(), JumpTime, Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Map_Reading(), Mesh::material, meshList, npc, NPC::DOT::Nposition, oreMaterial_arr, pickAxeRotation, pickAxeTranslation, Sound::playMusic(), rawMaterial::pos, Light::position, potatoRotate, Light::power, PressTime, projectionStack, rm_coolDown, rm_coolDownLimit, NPC::robot1, NPC::robot2, NPC::robot3, Position::Set(), Component::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), sound, NPC::spacebody, NPC::spacerocket, NPC::spacewing, Light::spotDirection, startCoolDdown, startRMcoolDown, storyPosition, storyShow, swordRotation, swordTranslation, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POSITION, U_LIGHT2_POWER, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_TYPE, U_LIGHT3_COLOR, U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT, U_LIGHT3_KC, U_LIGHT3_KL, U_LIGHT3_KQ, U_LIGHT3_POSITION, U_LIGHT3_POWER, U_LIGHT3_SPOTDIRECTION, U_LIGHT3_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, usingGun, usingPickAxe, usingSword, w_x, w_y, weaponChoice, x, and y.
void SP2::Map_Reading () private
Definition at line 1517 of file SP2.cpp.
References Map.
Referenced by Init().
void SP2::Map_Rendering () private
Definition at line 1535 of file SP2.cpp.
References camera, GEO_POTATO, GEO_PYRAMIDNEW, GEO_PYRAMIDPILLAR, GEO_PYRAMIDWALL, Map, meshList, modelStack, MS::PopMatrix(), Camera::position, potatoRotate, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Size, MS::Translate(), X_Displacement, Vector3::y, and Z_Displacement.
Referenced by Render().
void SP2::ObjectsHolding (Mesh * mesh, float size) private
Definition at line 1464 of file SP2.cpp.
References camera, followx, followy, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2::Render () virtual
animation for it gg up
Implements Scene.
Definition at line 1038 of file SP2.cpp.
References SharedData::bomb, SharedData::bullet, bullet_arr, camera, NPC::DOT::canInteract, CollisionDetector::collideByDist(), deltaTime, detectCollision, NPC::dialogue, NPC::dialoguePlus, NPC::door, Vector3::Dot(), SharedData::egg, Enemy_Rendering(), SharedData::enemycounter, explosionLoc, explosionLocRotateX, explosionLocRotateY, explosionScale, fixrocket, fixwing, followx, followy, GEO_AMMOICON, GEO_BOMBICON, GEO_BULLETSKIN, GEO_CCTV, GEO_CROSSHAIR, GEO_EGGICON, GEO_EXPLOSION2, GEO_GOLDICON, GEO_GUN, GEO_GUNICON, GEO_MOONBALL, GEO_OREICON, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_PYRAMIDDOOR, GEO_PYRAMIDFLOOR, GEO_QUAD, GEO_ROBOT, GEO_ROBOT1, GEO_ROBOTB, GEO_ROBOTH, GEO_SPACESHIP, GEO_STORY1, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, SharedData::GetInstance(), SharedData::gold, gun, gunRotation, gunTranslation, holdingcctv, NPC::interactDia, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, Map_Rendering(), meshList, SharedData::mineral, modelStack, my_arr, npc, NPC::DOT::Nposition, ObjectsHolding(), oreMaterial_arr, parts, pickaxe, pickAxeRotation, pickAxeTranslation, pickuprocket, pickupwing, playExplosionAnimation, MS::PopMatrix(), rawMaterial::pos, Camera::position, Light::position, potatoRotate, MS::PushMatrix(), SharedData::INVENTORY::quantity, RenderMesh(), RenderQuadOnScreen(), RenderSkybox(), RenderTextOnScreen(), NPC::DOT::robot, NPC::robot1, robot1rotation, NPC::robot2, NPC::robot3, MS::Rotate(), MS::Scale(), NPC::spacebody, NPC::spacerocket, NPC::spacewing, Light::spotDirection, storyDismiss, storyPosition, sword, swordRotation, swordTranslation, Camera::target, throwup, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, U_LIGHT2_POSITION, U_LIGHT2_SPOTDIRECTION, Camera::up, Camera3::view, viewStack, w_y, Position::x, Vector3::x, x, Position::y, Vector3::y, y, Position::z, and Vector3::z.
void SP2::RenderMesh (Mesh * mesh, bool enableLight) private
Definition at line 827 of file SP2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, Lighting9, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Enemy_Rendering(), EquipmentHolding(), Map_Rendering(), ObjectsHolding(), Render(), RenderObjects(), RenderQuadOnScreen(), and RenderSkybox().
void SP2::RenderObjects (Mesh * mesh, float size, float x, float y, float z) private
Definition at line 1456 of file SP2.cpp.
References modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Scale(), and MS::Translate().
void SP2::RenderQuadOnScreen (Mesh * mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z) private
Renders obj and quads on screen.
Parameters
mesh Takes in which mesh to render out
size Scale of the mesh to render out
x,y,z The position of the mesh
rotate,rx,ry,rz The degree to rotate and which one to rotate
z Z layering of the quad/obj
Exceptions
None
Returns
None
Definition at line 958 of file SP2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void SP2::RenderSkybox () private
Definition at line 978 of file SP2.cpp.
References GEO_BACK1, GEO_BOTTOM1, GEO_FRONT1, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), SBSCALE1, MS::Scale(), and MS::Translate().
Referenced by Render().
void SP2::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 867 of file SP2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SP2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 893 of file SP2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void SP2::Update (double dt) virtual
when untoggle below runs agains
restrrrict movement NEED TO MAKE SURE ITS 2ND TIME
make sure camera mode dont exit and reenter
Implements Scene.
Definition at line 419 of file SP2.cpp.
References animation, b_coolDown, b_coolDownLimit, SharedData::bullet, bullet, bullet_arr, cam1, camera, Camera3::cameraRotate, NPC::DOT::canGoThrough, Character_Movement(), CollisionDetector::collideByDist(), NPC::DOT::Collision, coolDownTime, deltaTime, detectCollision, NPC::dialoguePlus, NPC::door, NPC::Door(), Vector3::Dot(), enemy, Enemy_Updating(), Animation::explosion(), explosionLoc, explosionLocRotateX, explosionLocRotateY, explosionScale, fixrocket, fixwing, followx, followy, SharedData::gameState, GEO_RMBIG, GEO_RMMEDIUM, GEO_RMSMALL, SharedData::GetInstance(), gun, gunTranslation, holdingcctv, rawMaterial::hp, NPC::interactDia, rawMaterial::isAlive, Application::IsKeyPressed(), Lighting9, meshList, Animation::Mine(), SharedData::mineral, mouse, Mouse::MouseUpdate(), Animation::moveGun(), movement, Animation::moveSword(), my_arr, newcameraposition, npc, NPC::NPCmovement(), NPC::NPCmovement2(), NPC::DOT::Nposition, oldcameraposition, oreMaterial_arr, parts, pickaxe, pickAxeRotation, pickAxeTranslation, pickuprocket, pickupwing, playExplosionAnimation, playMiningAnimation, Sound::playSE(), playShootingAnimation, playSlashingAnimation, rawMaterial::pos, Camera::position, potatoRotate, SharedData::INVENTORY::quantity, rm_coolDown, rm_coolDownLimit, NPC::DOT::robot, NPC::robot1, robot1rotation, NPC::robot3, NPC::Scene1(), SharedData::SCENE2, rawMaterial::shape, Animation::Shoot(), Animation::Slash(), sound, NPC::spacebody, NPC::spacerocket, NPC::spacewing, startCoolDdown, startRMcoolDown, SharedData::stateCheck, Sound::stopMusic(), storyDismiss, storyPosition, storyShow, sword, CollisionDetector::swordCollision(), swordRotation, swordTranslation, Mesh::textureID, toggle, usingGun, usingPickAxe, usingSword, Camera3::view, weaponChoice, Vector3::x, Vector3::y, and Vector3::z.
void SP2::UpdateMenu () private
Field Documentation
Animation SP2::animation private
Definition at line 321 of file SP2.h.
Referenced by Update().
int SP2::b_Ammo private
Definition at line 255 of file SP2.h.
double SP2::b_coolDown private
Definition at line 252 of file SP2.h.
Referenced by Init(), and Update().
double SP2::b_coolDownLimit private
Definition at line 253 of file SP2.h.
Referenced by Init(), and Update().
Bullet SP2::bullet private
Definition at line 264 of file SP2.h.
Referenced by Update().
vector<Bullet*> SP2::bullet_arr private
Definition at line 250 of file SP2.h.
Referenced by Render(), and Update().
bool SP2::cam1 = false private
Definition at line 292 of file SP2.h.
Referenced by Update().
Camera3 SP2::camera private
Definition at line 246 of file SP2.h.
Referenced by Character_Movement(), Enemy_Updating(), EquipmentHolding(), Init(), Map_Rendering(), ObjectsHolding(), Render(), and Update().
float SP2::coolDownTime private
Definition at line 303 of file SP2.h.
Referenced by Update().
float SP2::deltaTime private
Definition at line 263 of file SP2.h.
Referenced by Render(), and Update().
CollisionDetector SP2::detectCollision private
Definition at line 319 of file SP2.h.
Referenced by Render(), and Update().
Enemy SP2::enemy[5] private
Definition at line 277 of file SP2.h.
Referenced by Character_Movement(), Enemy_Rendering(), Enemy_Updating(), and Update().
Vector3 SP2::explosionLoc private
Definition at line 346 of file SP2.h.
Referenced by Init(), Render(), and Update().
float SP2::explosionLocRotateX private
Definition at line 348 of file SP2.h.
Referenced by Init(), Render(), and Update().
float SP2::explosionLocRotateY private
Definition at line 347 of file SP2.h.
Referenced by Init(), Render(), and Update().
float SP2::explosionScale private
Definition at line 345 of file SP2.h.
Referenced by Init(), Render(), and Update().
bool SP2::fixrocket = false private
Definition at line 302 of file SP2.h.
Referenced by Render(), and Update().
bool SP2::fixwing = false private
Definition at line 301 of file SP2.h.
Referenced by Render(), and Update().
float SP2::followx = 0 private
Definition at line 299 of file SP2.h.
Referenced by Character_Movement(), EquipmentHolding(), ObjectsHolding(), Render(), and Update().
float SP2::followy = 0 private
Definition at line 300 of file SP2.h.
Referenced by Character_Movement(), EquipmentHolding(), ObjectsHolding(), Render(), and Update().
int SP2::gun private
Definition at line 220 of file SP2.h.
Referenced by Init(), Render(), and Update().
float SP2::gunRotation private
Definition at line 324 of file SP2.h.
Referenced by Init(), and Render().
float SP2::gunTranslation private
Definition at line 326 of file SP2.h.
Referenced by Init(), Render(), and Update().
bool SP2::holdingcctv = false private
Definition at line 294 of file SP2.h.
Referenced by Render(), and Update().
float SP2::JumpTime private
Definition at line 315 of file SP2.h.
Referenced by Init().
Light SP2::light[8] private
Definition at line 233 of file SP2.h.
Referenced by Character_Movement(), Init(), and Render().
float SP2::LSPEED = 10.f private
Definition at line 228 of file SP2.h.
unsigned SP2::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 212 of file SP2.h.
unsigned SP2::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 210 of file SP2.h.
unsigned SP2::m_parameters[U_TOTAL] private
Definition at line 214 of file SP2.h.
Referenced by Character_Movement(), Init(), Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned SP2::m_programID private
Definition at line 213 of file SP2.h.
Referenced by Exit(), and Init().
unsigned SP2::m_vertexArrayID private
Definition at line 209 of file SP2.h.
Referenced by Exit(), and Init().
unsigned SP2::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 211 of file SP2.h.
char SP2::Map[20][20]
Definition at line 194 of file SP2.h.
Referenced by Character_Movement(), Enemy_Updating(), Map_Reading(), and Map_Rendering().
Mesh* SP2::meshList[NUM_GEOMETRY] private
Definition at line 225 of file SP2.h.
Referenced by Enemy_Rendering(), Init(), Map_Rendering(), Render(), RenderSkybox(), and Update().
MS SP2::modelStack private
Definition at line 227 of file SP2.h.
Referenced by Enemy_Rendering(), EquipmentHolding(), Map_Rendering(), ObjectsHolding(), Render(), RenderMesh(), RenderObjects(), RenderQuadOnScreen(), RenderSkybox(), RenderText(), and RenderTextOnScreen().
Mouse SP2::mouse private
Definition at line 318 of file SP2.h.
Referenced by Update().
bool SP2::movement = true private
Definition at line 293 of file SP2.h.
Referenced by Character_Movement(), and Update().
float SP2::moveSkyBoxX = 0.f private
Definition at line 230 of file SP2.h.
float SP2::moveSkyBoxZ = 91.f private
Definition at line 229 of file SP2.h.
vector<string> SP2::my_arr private
Definition at line 249 of file SP2.h.
Referenced by Dialogue(), Render(), and Update().
string SP2::new_line private
Definition at line 241 of file SP2.h.
Referenced by Dialogue().
Vector3 SP2::newcameraposition = (0, 0, 0) private
Definition at line 287 of file SP2.h.
Referenced by Update().
NPC SP2::npc private
Definition at line 217 of file SP2.h.
Referenced by Character_Movement(), Init(), Render(), and Update().
Objects SP2::object[Num_Object] private
Definition at line 311 of file SP2.h.
Objects SP2::object_on_hand private
Definition at line 312 of file SP2.h.
Objects SP2::objects private
Definition at line 265 of file SP2.h.
Vector3 SP2::oldcameraposition = (0, 0, 0) private
Definition at line 288 of file SP2.h.
Referenced by Update().
rawMaterial SP2::oreMaterial_arr[3] private
Definition at line 340 of file SP2.h.
Referenced by Init(), Render(), and Update().
int SP2::parts = 0 private
Definition at line 219 of file SP2.h.
Referenced by Render(), and Update().
int SP2::pickaxe private
Definition at line 221 of file SP2.h.
Referenced by Render(), and Update().
float SP2::pickAxeRotation private
Definition at line 323 of file SP2.h.
Referenced by Init(), Render(), and Update().
float SP2::pickAxeTranslation private
Definition at line 328 of file SP2.h.
Referenced by Init(), Render(), and Update().
bool SP2::pickuprocket = false private
Definition at line 298 of file SP2.h.
Referenced by Render(), and Update().
bool SP2::pickupwing = false private
Definition at line 297 of file SP2.h.
Referenced by Render(), and Update().
bool SP2::playExplosionAnimation private
Definition at line 333 of file SP2.h.
Referenced by Render(), and Update().
bool SP2::playMiningAnimation private
Definition at line 332 of file SP2.h.
Referenced by Update().
bool SP2::playShootingAnimation private
Definition at line 331 of file SP2.h.
Referenced by Update().
bool SP2::playSlashingAnimation private
Definition at line 330 of file SP2.h.
Referenced by Update().
float SP2::potatoRotate private
Definition at line 231 of file SP2.h.
Referenced by Init(), Map_Rendering(), Render(), and Update().
float SP2::PressTime private
Definition at line 316 of file SP2.h.
Referenced by Init().
MS SP2::projectionStack private
Definition at line 227 of file SP2.h.
Referenced by Init(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
double SP2::rm_coolDown private
Definition at line 341 of file SP2.h.
Referenced by Init(), and Update().
double SP2::rm_coolDownLimit private
Definition at line 342 of file SP2.h.
Referenced by Init(), and Update().
bool SP2::robot1moved = false private
Definition at line 273 of file SP2.h.
bool SP2::robot1rotate = false private
Definition at line 274 of file SP2.h.
float SP2::robot1rotation = 0 private
Definition at line 275 of file SP2.h.
Referenced by Render(), and Update().
Vector3 SP2::RobotPosition1 private
Definition at line 251 of file SP2.h.
string SP2::shop private
Definition at line 305 of file SP2.h.
float SP2::Size = 15
Definition at line 195 of file SP2.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
Sound SP2::sound private
Definition at line 247 of file SP2.h.
Referenced by Init(), and Update().
bool SP2::startCoolDdown private
Definition at line 254 of file SP2.h.
Referenced by Init(), and Update().
bool SP2::startRMcoolDown private
Definition at line 343 of file SP2.h.
Referenced by Init(), and Update().
string SP2::story private
Definition at line 261 of file SP2.h.
bool SP2::storyDismiss private
Definition at line 259 of file SP2.h.
Referenced by Render(), and Update().
float SP2::storyPosition private
Definition at line 258 of file SP2.h.
Referenced by Init(), Render(), and Update().
bool SP2::storyShow private
Definition at line 260 of file SP2.h.
Referenced by Init(), and Update().
int SP2::sword private
Definition at line 222 of file SP2.h.
Referenced by Render(), and Update().
float SP2::swordRotation private
Definition at line 322 of file SP2.h.
Referenced by Init(), Render(), and Update().
float SP2::swordTranslation private
Definition at line 327 of file SP2.h.
Referenced by Init(), Render(), and Update().
int SP2::T_object_Num private
Definition at line 313 of file SP2.h.
bool SP2::throwbomb = false private
Definition at line 289 of file SP2.h.
float SP2::throwingdown = 0 private
Definition at line 284 of file SP2.h.
float SP2::throwingforward = 0 private
Definition at line 285 of file SP2.h.
bool SP2::thrown = false private
Definition at line 290 of file SP2.h.
float SP2::throwup = 0 private
Definition at line 286 of file SP2.h.
Referenced by Render().
bool SP2::toggle = false private
Definition at line 291 of file SP2.h.
Referenced by Update().
bool SP2::usingGun private
Definition at line 336 of file SP2.h.
Referenced by Init(), and Update().
bool SP2::usingPickAxe private
Definition at line 337 of file SP2.h.
Referenced by Init(), and Update().
bool SP2::usingSword private
Definition at line 335 of file SP2.h.
Referenced by Init(), and Update().
MS SP2::viewStack private
Definition at line 227 of file SP2.h.
Referenced by Render(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
int SP2::w_x private
Definition at line 270 of file SP2.h.
Referenced by Init().
int SP2::w_y private
Definition at line 271 of file SP2.h.
Referenced by Init(), and Render().
int SP2::weaponChoice private
Definition at line 338 of file SP2.h.
Referenced by Init(), and Update().
int SP2::x private
Definition at line 268 of file SP2.h.
Referenced by Init(), and Render().
float SP2::X_Displacement = -100
Definition at line 197 of file SP2.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
int SP2::y private
Definition at line 269 of file SP2.h.
Referenced by Init(), and Render().
float SP2::Z_Displacement = 0
Definition at line 196 of file SP2.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
The documentation for this class was generated from the following files:
MyGraphics/Source/SP2.h
MyGraphics/Source/SP2.cpp