My Application: Sound Class Reference
Sound Class Reference
Creates sound engine and allows music to be played.
#include <Sound.h>
Public Member Functions
Sound ()
~Sound ()
void playMusic (string Music)
Plays the background music looped.
void stopMusic (string Music)
Stop certain music when called.
void playSE (string Music)
Plays the sound effect no loop.
Private Attributes
irrklang::ISoundEngine * musicEngine
irrklang::ISound * Song
irrklang::ISound * SoundEffect
Detailed Description
Creates sound engine and allows music to be played.
Class Sound:
Definition at line 25 of file Sound.h.
Constructor & Destructor Documentation
Sound::Sound ()
Definition at line 12 of file Sound.cpp.
References irrklang::createIrrKlangDevice(), and musicEngine.
Sound::~Sound ()
Definition at line 16 of file Sound.cpp.
Member Function Documentation
void Sound::playMusic (string Music)
Plays the background music looped.
Parameters
Music Takes in path of background music to play
Exceptions
None
Returns
None
Definition at line 32 of file Sound.cpp.
References musicEngine, irrklang::ISoundEngine::play2D(), and Song.
Referenced by SceneWin::Init(), Cutscene::Init(), Shop::Init(), SP2::Init(), Scene2::Init(), and Scene3::Init().
void Sound::playSE (string Music)
Plays the sound effect no loop.
Parameters
Music Takes in path of sound effect to play
Exceptions
None
Returns
None
Definition at line 48 of file Sound.cpp.
References musicEngine, irrklang::ISoundEngine::play2D(), and SoundEffect.
Referenced by StartCutScene::Init(), NPC::Scene1(), NPC::Shop(), Shop::ShopOptions(), Shop::Update(), SP2::Update(), Scene2::Update(), Scene3::Update(), and Shop::userInput().
void Sound::stopMusic (string Music)
Stop certain music when called.
Parameters
Music Takes in path of background music/sound effect to stop
Exceptions
None
Returns
None
Definition at line 64 of file Sound.cpp.
References Song, and irrklang::ISound::stop().
Referenced by SceneWin::Update(), Cutscene::Update(), Shop::Update(), and SP2::Update().
Field Documentation
irrklang::ISoundEngine* Sound::musicEngine private
Definition at line 36 of file Sound.h.
Referenced by playMusic(), playSE(), and Sound().
irrklang::ISound* Sound::Song private
Definition at line 37 of file Sound.h.
Referenced by playMusic(), and stopMusic().
irrklang::ISound* Sound::SoundEffect private
Definition at line 38 of file Sound.h.
Referenced by playSE().
The documentation for this class was generated from the following files:
MyGraphics/Source/Sound.h
MyGraphics/Source/Sound.cpp