My Application: Shop Class Reference
Shop Class Reference
Renders the shop scene with needed meshes and takes care of shop interactables.
#include <Shop.h>
Public Member Functions
Shop ()
Default constructor.
~Shop ()
Default destructor.
virtual void Init ()
Initializes for shop scene, any booleans/strings/floats and meshes.
virtual void Update (double dt)
Updates the scene every frame (Animation/booleans/music etc)
virtual void Render ()
The main render function for this scene, renders any text/meshes.
virtual void Exit ()
Delete scene.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_SHOPKEEPER3D = 0, GEO_SHOPKEEPER, GEO_TABLE, GEO_REF_AXES,
GEO_REF_QUAD, GEO_LIGHTBALL, GEO_AMMOICON, GEO_GOLDICON,
GEO_EGGICON, GEO_BOMBICON, GEO_OREICON, GEO_SPACEDOOR,
GEO_QUAD, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1,
GEO_BOTTOM1, GEO_FRONT1, GEO_BACK1, GEO_SHOPWALL,
GEO_TEXT, GEO_WALL, GEO_OUTER, GEO_SHOPICON,
GEO_CEILING, GEO_FLOOR, GEO_SPACESHIP, GEO_PLANEBODY,
GEO_PLANEWING, GEO_PLANEROCKET, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Mesh rendering function.
void RenderSkybox ()
Renders the skybox on screen with rotation, scaling done.
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Renders text on screen in the game.
void RenderQuadOnScreen (Mesh *mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z)
Renders obj and quads on screen.
void Dialogue (string filename)
Pushes in the shop scene into array from text file, allows easy changes.
void ShopOptions ()
Checks for if player is in each other the "shop/buying/selling" scene and show out the options player can use.
void userInput ()
Checks for player input in "Shop/Buy/Selling".
Private Attributes
unsigned m_vertexArrayID
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Mouse mouse
Mesh * meshList [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
float LSPEED = 10.f
string new_line
Camera3 camera
MenuShop::SHOP_OPTION shop
MenuShop::SHOP_BUY buy
MenuShop::SHOP_SELL sell
string Input
vector< string > my_arr
float deltaTime
float icon
float icon2
float menuIcon
NPC npc
Sound sound
float JumpTime
float PressTime
float spaceDoor
string description
string shopInput
bool b_gold
bool g_gold
string nomore
bool none
float coolDown
bool sell_gold
CollisionDetector detectCollision
int gold
Detailed Description
Renders the shop scene with needed meshes and takes care of shop interactables.
Class Shop:
Definition at line 41 of file Shop.h.
Member Enumeration Documentation
enum Shop::GEOMETRY_TYPE private
Enumerator
GEO_SHOPKEEPER3D
GEO_SHOPKEEPER
GEO_TABLE
GEO_REF_AXES
GEO_REF_QUAD
GEO_LIGHTBALL
GEO_AMMOICON
GEO_GOLDICON
GEO_EGGICON
GEO_BOMBICON
GEO_OREICON
GEO_SPACEDOOR
GEO_QUAD
GEO_LEFT1
GEO_RIGHT1
GEO_TOP1
GEO_BOTTOM1
GEO_FRONT1
GEO_BACK1
GEO_SHOPWALL
GEO_TEXT
GEO_WALL
GEO_OUTER
GEO_SHOPICON
GEO_CEILING
GEO_FLOOR
GEO_SPACESHIP
GEO_PLANEBODY
GEO_PLANEWING
GEO_PLANEROCKET
NUM_GEOMETRY
Definition at line 43 of file Shop.h.
enum Shop::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 80 of file Shop.h.
Constructor & Destructor Documentation
Shop::Shop ()
Default constructor.
Exceptions
None
Returns
None
Definition at line 27 of file Shop.cpp.
Shop::~Shop ()
Default destructor.
Exceptions
None
Returns
None
Definition at line 39 of file Shop.cpp.
Member Function Documentation
void Shop::Dialogue (string filename) private
Pushes in the shop scene into array from text file, allows easy changes.
Exceptions
None
Returns
None
Definition at line 515 of file Shop.cpp.
References my_arr, and new_line.
Referenced by Init().
void Shop::Exit () virtual
Delete scene.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 932 of file Shop.cpp.
References m_programID, and m_vertexArrayID.
void Shop::Init () virtual
Initializes for shop scene, any booleans/strings/floats and meshes.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 51 of file Shop.cpp.
References camera, Camera3::cameraRotate, Dialogue(), MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRepeatQuad(), MeshBuilder::GenerateText(), GEO_AMMOICON, GEO_BACK1, GEO_BOMBICON, GEO_BOTTOM1, GEO_CEILING, GEO_EGGICON, GEO_FRONT1, GEO_GOLDICON, GEO_LEFT1, GEO_OREICON, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_QUAD, GEO_REF_AXES, GEO_RIGHT1, GEO_SHOPICON, GEO_SHOPKEEPER, GEO_SHOPKEEPER3D, GEO_SHOPWALL, GEO_SPACEDOOR, GEO_TABLE, GEO_TEXT, GEO_TOP1, icon2, Camera3::Init(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, npc, NPC::DOT::Nposition, Sound::playMusic(), PressTime, projectionStack, NPC::seller, Component::Set(), Mtx44::SetToPerspective(), sound, NPC::spaceDoor, Mesh::textureID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and Vector3::y.
void Shop::Render () virtual
The main render function for this scene, renders any text/meshes.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 728 of file Shop.cpp.
References b_gold, SharedData::bomb, SharedData::bullet, camera, NPC::DOT::canInteract, coolDown, deltaTime, description, SharedData::egg, GEO_AMMOICON, GEO_BOMBICON, GEO_EGGICON, GEO_GOLDICON, GEO_OREICON, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_QUAD, GEO_SHOPICON, GEO_SHOPKEEPER, GEO_SHOPKEEPER3D, GEO_SHOPWALL, GEO_SPACEDOOR, GEO_TABLE, GEO_TEXT, SharedData::GetInstance(), SharedData::gold, icon2, NPC::interactDia, MS::LoadIdentity(), MS::LookAt(), meshList, SharedData::mineral, modelStack, my_arr, nomore, none, npc, NPC::DOT::Nposition, MS::PopMatrix(), Camera::position, MS::PushMatrix(), SharedData::INVENTORY::quantity, RenderMesh(), RenderQuadOnScreen(), RenderSkybox(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), NPC::seller, shopInput, NPC::spaceDoor, Camera::target, MS::Translate(), Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void Shop::RenderMesh (Mesh * mesh, bool enableLight) private
Mesh rendering function.
Exceptions
None
Returns
None
Definition at line 535 of file Shop.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MODELVIEW, U_MVP, and viewStack.
Referenced by Render(), RenderQuadOnScreen(), and RenderSkybox().
void Shop::RenderQuadOnScreen (Mesh * mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z) private
Renders obj and quads on screen.
Parameters
mesh Takes in which mesh to render out
size Scale of the mesh to render out
x,y,z The position of the mesh
rotate,rx,ry,rz The degree to rotate and which one to rotate
z Z layering of the quad/obj
Exceptions
None
Returns
None
Definition at line 632 of file Shop.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void Shop::RenderSkybox () private
Renders the skybox on screen with rotation, scaling done.
Exceptions
None
Returns
None
Definition at line 660 of file Shop.cpp.
References GEO_BACK1, GEO_BOTTOM1, GEO_FRONT1, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), SBSCALE1, MS::Scale(), and MS::Translate().
Referenced by Render().
void Shop::RenderText (Mesh * mesh, std::string text, Color color) private
void Shop::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Renders text on screen in the game.
Exceptions
None
Returns
None
Definition at line 568 of file Shop.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void Shop::ShopOptions () private
Checks for if player is in each other the "shop/buying/selling" scene and show out the options player can use.
Exceptions
None
Returns
None
Definition at line 194 of file Shop.cpp.
References b_gold, SharedData::bomb, SharedData::bullet, buy, coolDown, deltaTime, description, SharedData::egg, SharedData::GetInstance(), SharedData::gold, gold, icon2, Application::IsKeyPressed(), SharedData::mineral, nomore, none, Sound::playSE(), PressTime, SharedData::INVENTORY::quantity, MenuShop::S_BACK, MenuShop::S_BUY, MenuShop::S_SELL, MenuShop::SB_AMMO, MenuShop::SB_BACK, MenuShop::SB_BOMB, sell, shop, shopInput, sound, MenuShop::SS_AMMO, MenuShop::SS_BACK, MenuShop::SS_EGG, and MenuShop::SS_ORE.
Referenced by Update().
void Shop::Update (double dt) virtual
Updates the scene every frame (Animation/booleans/music etc)
Exceptions
None
Returns
None
Implements Scene.
Definition at line 462 of file Shop.cpp.
References camera, CollisionDetector::collideByDist(), coolDown, deltaTime, detectCollision, Application::IsKeyPressed(), mouse, Mouse::MouseUpdate(), npc, NPC::DOT::Nposition, Sound::playSE(), Camera::position, PressTime, NPC::seller, NPC::Shop(), shopInput, ShopOptions(), sound, Sound::stopMusic(), NPC::stopMusic, Camera3::Update(), and userInput().
void Shop::userInput () private
Checks for player input in "Shop/Buy/Selling".
Exceptions
None
Returns
None
Definition at line 380 of file Shop.cpp.
References buy, deltaTime, icon2, Application::IsKeyPressed(), Sound::playSE(), PressTime, MenuShop::S_BUY, MenuShop::S_MAX, MenuShop::SB_AMMO, MenuShop::SB_MAX, sell, shop, shopInput, sound, MenuShop::SS_AMMO, and MenuShop::SS_MAX.
Referenced by Update().
Field Documentation
bool Shop::b_gold private
Definition at line 153 of file Shop.h.
Referenced by Render(), and ShopOptions().
MenuShop::SHOP_BUY Shop::buy private
Definition at line 133 of file Shop.h.
Referenced by ShopOptions(), and userInput().
Camera3 Shop::camera private
Definition at line 130 of file Shop.h.
Referenced by Init(), Render(), and Update().
float Shop::coolDown private
Definition at line 157 of file Shop.h.
Referenced by Render(), ShopOptions(), and Update().
float Shop::deltaTime private
Definition at line 139 of file Shop.h.
Referenced by Render(), ShopOptions(), Update(), and userInput().
string Shop::description private
Definition at line 151 of file Shop.h.
Referenced by Render(), and ShopOptions().
CollisionDetector Shop::detectCollision private
Definition at line 159 of file Shop.h.
Referenced by Update().
bool Shop::g_gold private
Definition at line 154 of file Shop.h.
int Shop::gold private
Definition at line 160 of file Shop.h.
Referenced by ShopOptions().
float Shop::icon private
Definition at line 141 of file Shop.h.
float Shop::icon2 private
Definition at line 142 of file Shop.h.
Referenced by Init(), Render(), ShopOptions(), and userInput().
string Shop::Input private
Definition at line 136 of file Shop.h.
float Shop::JumpTime private
Definition at line 148 of file Shop.h.
float Shop::LSPEED = 10.f private
Definition at line 121 of file Shop.h.
unsigned Shop::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 111 of file Shop.h.
unsigned Shop::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 109 of file Shop.h.
unsigned Shop::m_parameters[U_TOTAL] private
Definition at line 113 of file Shop.h.
Referenced by Init(), RenderMesh(), and RenderTextOnScreen().
unsigned Shop::m_programID private
Definition at line 112 of file Shop.h.
Referenced by Exit(), and Init().
unsigned Shop::m_vertexArrayID private
Definition at line 108 of file Shop.h.
Referenced by Exit(), and Init().
unsigned Shop::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 110 of file Shop.h.
float Shop::menuIcon private
Definition at line 143 of file Shop.h.
Mesh* Shop::meshList[NUM_GEOMETRY] private
Definition at line 118 of file Shop.h.
Referenced by Init(), Render(), and RenderSkybox().
MS Shop::modelStack private
Definition at line 120 of file Shop.h.
Referenced by Render(), RenderMesh(), RenderQuadOnScreen(), RenderSkybox(), and RenderTextOnScreen().
Mouse Shop::mouse private
Definition at line 115 of file Shop.h.
Referenced by Update().
vector<string> Shop::my_arr private
Definition at line 137 of file Shop.h.
Referenced by Dialogue(), and Render().
string Shop::new_line private
Definition at line 129 of file Shop.h.
Referenced by Dialogue().
string Shop::nomore private
Definition at line 155 of file Shop.h.
Referenced by Render(), and ShopOptions().
bool Shop::none private
Definition at line 156 of file Shop.h.
Referenced by Render(), and ShopOptions().
NPC Shop::npc private
Definition at line 145 of file Shop.h.
Referenced by Init(), Render(), and Update().
float Shop::PressTime private
Definition at line 149 of file Shop.h.
Referenced by Init(), ShopOptions(), Update(), and userInput().
MS Shop::projectionStack private
Definition at line 120 of file Shop.h.
Referenced by Init(), RenderMesh(), RenderQuadOnScreen(), and RenderTextOnScreen().
MenuShop::SHOP_SELL Shop::sell private
Definition at line 134 of file Shop.h.
Referenced by ShopOptions(), and userInput().
bool Shop::sell_gold private
Definition at line 158 of file Shop.h.
MenuShop::SHOP_OPTION Shop::shop private
Definition at line 132 of file Shop.h.
Referenced by ShopOptions(), and userInput().
string Shop::shopInput private
Definition at line 152 of file Shop.h.
Referenced by Render(), ShopOptions(), Update(), and userInput().
Sound Shop::sound private
Definition at line 146 of file Shop.h.
Referenced by Init(), ShopOptions(), Update(), and userInput().
float Shop::spaceDoor private
Definition at line 150 of file Shop.h.
MS Shop::viewStack private
Definition at line 120 of file Shop.h.
Referenced by Render(), RenderMesh(), RenderQuadOnScreen(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
MyGraphics/Source/Shop.h
MyGraphics/Source/Shop.cpp