My Application: SceneMenu Class Reference
SceneMenu Class Reference
Class objects, meshes to render, booleans, floats and strings.
#include <SceneMenu.h>
Public Member Functions
SceneMenu ()
Default constructor.
~SceneMenu ()
Default destructor.
virtual void Init ()
Initializes for menu scene, any booleans/strings/floats and meshes.
virtual void Update (double dt)
Updates the scene every frame.
virtual void Render ()
Main rendering.
virtual void Exit ()
Exits the scene and delete.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_REF_AXES = 0, GEO_QUAD, GEO_STAR, GEO_TEXT,
GEO_PATH, GEO_VENDING, GEO_COKE, GEO_INSTRUCTIONS,
GEO_CREDITS, GEO_PLANEWING, GEO_PLANEROCKET, GEO_PLANEBODY,
NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Renders mesh.
void UpdateMenu ()
Handles all switch cases for menu.
void RenderText (Mesh *mesh, std::string text, Color color)
Renders text.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Renders text on screen.
void RenderQuadOnScreen (Mesh *mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z)
Renders obj and quads on screen.
void RenderMenu ()
void Dialogue (string filename)
Pushes in the shop scene into array from text file, allows easy changes.
void setColor (int which, string color)
Setting color for when player presses up and down to each color in array.
void userInput ()
Handles user up and down input.
void mouseControl ()
Private Attributes
unsigned m_vertexArrayID
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
MenuShop menushop
bool clicked
Mesh * meshList [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
float LSPEED = 10.f
float moveSkyBoxZ = 91.f
float moveSkyBoxX = 0.f
bool Menu = true
bool exitGame = false
bool Options = false
string new_line
MenuShop::MENU choose
MenuShop::OPTION c_option
Application app
Camera3 camera
Sound sound
Color colorA [16]
Color colorBlue
Color colorNormal
int px
int py
bool instructions
bool credits
string Input
string color
vector< string > my_arr
float deltaTime
float menu_pos = 5
float icon
float icon2
float rotateCoke
float menuIcon
Detailed Description
Class objects, meshes to render, booleans, floats and strings.
Class SceneMenu:
Definition at line 35 of file SceneMenu.h.
Member Enumeration Documentation
enum SceneMenu::GEOMETRY_TYPE private
Enumerator
GEO_REF_AXES
GEO_QUAD
GEO_STAR
GEO_TEXT
GEO_PATH
GEO_VENDING
GEO_COKE
GEO_INSTRUCTIONS
GEO_CREDITS
GEO_PLANEWING
GEO_PLANEROCKET
GEO_PLANEBODY
NUM_GEOMETRY
Definition at line 37 of file SceneMenu.h.
enum SceneMenu::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 54 of file SceneMenu.h.
Constructor & Destructor Documentation
SceneMenu::SceneMenu ()
Default constructor.
Exceptions
None
Returns
None
Definition at line 33 of file SceneMenu.cpp.
SceneMenu::~SceneMenu ()
Default destructor.
Exceptions
None
Returns
None
Definition at line 45 of file SceneMenu.cpp.
Member Function Documentation
void SceneMenu::Dialogue (string filename) private
Pushes in the shop scene into array from text file, allows easy changes.
Exceptions
None
Returns
None
Definition at line 437 of file SceneMenu.cpp.
void SceneMenu::Exit () virtual
Exits the scene and delete.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 693 of file SceneMenu.cpp.
void SceneMenu::Init () virtual
Initializes for menu scene, any booleans/strings/floats and meshes.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 57 of file SceneMenu.cpp.
References MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), LoadShaders(), LoadTGA(), and Mtx44::SetToPerspective().
void SceneMenu::mouseControl () private
Definition at line 312 of file SceneMenu.cpp.
References MenuShop::CREDITS, SharedData::GAME, SharedData::gameState, SharedData::GetInstance(), MenuShop::HELP, Application::IsKeyPressed(), MenuShop::O_CREDIT, MenuShop::O_HELP, MenuShop::QUIT, SharedData::QUIT, MenuShop::STARTGAME, and SharedData::stateCheck.
void SceneMenu::Render () virtual
Main rendering.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 616 of file SceneMenu.cpp.
void SceneMenu::RenderMenu () private
void SceneMenu::RenderMesh (Mesh * mesh, bool enableLight) private
Renders mesh.
Exceptions
None
Returns
None
Definition at line 457 of file SceneMenu.cpp.
References Mtx44::a, Mesh::Render(), and Mesh::textureID.
void SceneMenu::RenderQuadOnScreen (Mesh * mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z) private
Renders obj and quads on screen.
Parameters
mesh Takes in which mesh to render out
size Scale of the mesh to render out
x,y,z The position of the mesh
rotate,rx,ry,rz The degree to rotate and which one to rotate
z Z layering of the quad/obj
Exceptions
None
Returns
None
Definition at line 589 of file SceneMenu.cpp.
References Mtx44::SetToOrtho().
void SceneMenu::RenderText (Mesh * mesh, std::string text, Color color) private
Renders text.
Exceptions
None
Returns
None
Definition at line 491 of file SceneMenu.cpp.
References Mtx44::a, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), and Mesh::textureID.
void SceneMenu::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Renders text on screen.
Exceptions
None
Returns
None
Definition at line 525 of file SceneMenu.cpp.
References Mtx44::a, Color::r, Mesh::Render(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), and Mesh::textureID.
void SceneMenu::setColor (int which, string color) private
Setting color for when player presses up and down to each color in array.
Parameters
which The array number in color to change
color Pass in which color to change
Exceptions
None
Returns
None
Definition at line 147 of file SceneMenu.cpp.
void SceneMenu::Update (double dt) virtual
Updates the scene every frame.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 405 of file SceneMenu.cpp.
void SceneMenu::UpdateMenu () private
Handles all switch cases for menu.
Exceptions
None
Returns
None
Definition at line 171 of file SceneMenu.cpp.
References MenuShop::CREDITS, SharedData::G_CUTSCENE, SharedData::gameState, SharedData::GetInstance(), MenuShop::HELP, Application::IsKeyPressed(), MenuShop::O_CREDIT, MenuShop::O_HELP, MenuShop::QUIT, SharedData::QUIT, MenuShop::STARTGAME, and SharedData::stateCheck.
void SceneMenu::userInput () private
Handles user up and down input.
Exceptions
None
Returns
None
Definition at line 281 of file SceneMenu.cpp.
References SharedData::GetInstance(), Application::IsKeyPressed(), MenuShop::MAX, and MenuShop::STARTGAME.
Field Documentation
Application SceneMenu::app private
Definition at line 112 of file SceneMenu.h.
MenuShop::OPTION SceneMenu::c_option private
Definition at line 110 of file SceneMenu.h.
Camera3 SceneMenu::camera private
Definition at line 113 of file SceneMenu.h.
MenuShop::MENU SceneMenu::choose private
Definition at line 109 of file SceneMenu.h.
bool SceneMenu::clicked private
Definition at line 92 of file SceneMenu.h.
string SceneMenu::color private
Definition at line 128 of file SceneMenu.h.
Color SceneMenu::colorA[16] private
Definition at line 118 of file SceneMenu.h.
Color SceneMenu::colorBlue private
Definition at line 119 of file SceneMenu.h.
Color SceneMenu::colorNormal private
Definition at line 120 of file SceneMenu.h.
bool SceneMenu::credits private
Definition at line 125 of file SceneMenu.h.
float SceneMenu::deltaTime private
Definition at line 130 of file SceneMenu.h.
bool SceneMenu::exitGame = false private
Definition at line 106 of file SceneMenu.h.
float SceneMenu::icon private
Definition at line 136 of file SceneMenu.h.
float SceneMenu::icon2 private
Definition at line 137 of file SceneMenu.h.
string SceneMenu::Input private
Definition at line 127 of file SceneMenu.h.
bool SceneMenu::instructions private
Definition at line 124 of file SceneMenu.h.
float SceneMenu::LSPEED = 10.f private
Definition at line 96 of file SceneMenu.h.
unsigned SceneMenu::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 86 of file SceneMenu.h.
unsigned SceneMenu::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 84 of file SceneMenu.h.
unsigned SceneMenu::m_parameters[U_TOTAL] private
Definition at line 88 of file SceneMenu.h.
unsigned SceneMenu::m_programID private
Definition at line 87 of file SceneMenu.h.
unsigned SceneMenu::m_vertexArrayID private
Definition at line 83 of file SceneMenu.h.
unsigned SceneMenu::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 85 of file SceneMenu.h.
bool SceneMenu::Menu = true private
Definition at line 105 of file SceneMenu.h.
float SceneMenu::menu_pos = 5 private
Definition at line 135 of file SceneMenu.h.
float SceneMenu::menuIcon private
Definition at line 139 of file SceneMenu.h.
MenuShop SceneMenu::menushop private
Definition at line 90 of file SceneMenu.h.
Mesh* SceneMenu::meshList[NUM_GEOMETRY] private
Definition at line 93 of file SceneMenu.h.
MS SceneMenu::modelStack private
Definition at line 95 of file SceneMenu.h.
float SceneMenu::moveSkyBoxX = 0.f private
Definition at line 98 of file SceneMenu.h.
float SceneMenu::moveSkyBoxZ = 91.f private
Definition at line 97 of file SceneMenu.h.
vector<string> SceneMenu::my_arr private
Definition at line 129 of file SceneMenu.h.
string SceneMenu::new_line private
Definition at line 108 of file SceneMenu.h.
bool SceneMenu::Options = false private
Definition at line 107 of file SceneMenu.h.
MS SceneMenu::projectionStack private
Definition at line 95 of file SceneMenu.h.
int SceneMenu::px private
Definition at line 121 of file SceneMenu.h.
int SceneMenu::py private
Definition at line 122 of file SceneMenu.h.
float SceneMenu::rotateCoke private
Definition at line 138 of file SceneMenu.h.
Sound SceneMenu::sound private
Definition at line 116 of file SceneMenu.h.
MS SceneMenu::viewStack private
Definition at line 95 of file SceneMenu.h.
The documentation for this class was generated from the following files:
MyGraphics/Source/SceneMenu.h
MyGraphics/Source/SceneMenu.cpp