My Application: Animation Class Reference
Animation Class Reference
#include <Animation.h>
Public Member Functions
Animation ()
~Animation ()
void Slash (double dt, float &targetRotation, bool &start)
void Shoot (double dt, float &targetTranslation, bool &start)
void Mine (double dt, float &targetRotation, bool &start)
void moveSword (double dt, float &targetTranslation, bool usingSword)
void moveGun (double dt, float &targetTranslation, bool usingGun)
void explosion (double dt, float &explosionScale, bool &playExplosion)
bool Update (double dt)
Data Fields
bool sliceUp
bool sliceDown
bool moveFront
bool moveBack
bool switchDown
bool switchUp
Detailed Description
Definition at line 5 of file Animation.h.
Constructor & Destructor Documentation
Animation::Animation ()
Definition at line 3 of file Animation.cpp.
References moveBack, moveFront, sliceDown, and sliceUp.
Animation::~Animation ()
Definition at line 7 of file Animation.cpp.
Member Function Documentation
void Animation::explosion (double dt, float & explosionScale, bool & playExplosion)
Definition at line 119 of file Animation.cpp.
Referenced by SP2::Update().
void Animation::Mine (double dt, float & targetRotation, bool & start)
Definition at line 51 of file Animation.cpp.
References sliceDown, and sliceUp.
Referenced by SP2::Update(), Scene2::Update(), and Scene3::Update().
void Animation::moveGun (double dt, float & targetTranslation, bool usingGun)
Definition at line 98 of file Animation.cpp.
Referenced by SP2::Update(), Scene2::Update(), and Scene3::Update().
void Animation::moveSword (double dt, float & targetTranslation, bool usingSword)
Definition at line 77 of file Animation.cpp.
Referenced by SP2::Update(), Scene2::Update(), and Scene3::Update().
void Animation::Shoot (double dt, float & targetTranslation, bool & start)
Definition at line 35 of file Animation.cpp.
Referenced by SP2::Update(), Scene2::Update(), and Scene3::Update().
void Animation::Slash (double dt, float & targetRotation, bool & start)
Definition at line 9 of file Animation.cpp.
References sliceDown, and sliceUp.
Referenced by SP2::Update(), Scene2::Update(), and Scene3::Update().
bool Animation::Update (double dt)
Field Documentation
bool Animation::moveBack
Definition at line 21 of file Animation.h.
Referenced by Animation().
bool Animation::moveFront
Definition at line 20 of file Animation.h.
Referenced by Animation().
bool Animation::sliceDown
Definition at line 19 of file Animation.h.
Referenced by Animation(), Mine(), and Slash().
bool Animation::sliceUp
Definition at line 18 of file Animation.h.
Referenced by Animation(), Mine(), and Slash().
bool Animation::switchDown
Definition at line 23 of file Animation.h.
bool Animation::switchUp
Definition at line 24 of file Animation.h.
The documentation for this class was generated from the following files:
MyGraphics/Source/Animation.h
MyGraphics/Source/Animation.cpp