My Application: Scene2 Class Reference
Scene2 Class Reference
Class objects, meshes to render, booleans, floats and strings.
#include <Scene2.h>
Public Member Functions
Scene2 ()
Default constructor.
~Scene2 ()
Default destructor.
virtual void Init ()
Initializes for 2nd scene.
virtual void Update (double dt)
Updates the scene every frame (Animation/booleans/music etc)
virtual void Render ()
Main rendering function.
virtual void Exit ()
Exit and delete scene.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
char Map [20][20]
float Size = 15
float Z_Displacement = 0
float X_Displacement = -100
Private Types
enum GEOMETRY_TYPE {
GEO_REF_AXES = 0, GEO_REF_QUAD, GEO_QUAD, GEO_ENEMY,
GEO_CROSSHAIR, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1,
GEO_BOTTOM1, GEO_FRONT1, GEO_BACK1, GEO_STAR,
GEO_STORY1, GEO_TEXT, GEO_AMMOICON, GEO_GOLDICON,
GEO_EGGICON, GEO_BOMBICON, GEO_OREICON, GEO_GUNICON,
GEO_PICKAXEICON, GEO_SWORDICON, GEO_BOMB, GEO_CCTV,
GEO_EGG, GEO_BAG, GEO_RING, GEO_PRISM,
GEO_SPEHERE, GEO_BULLET, GEO_ROBOTH, GEO_ROBOTB,
GEO_ROBOT, GEO_ROBOT1, GEO_ROBOT2, GEO_SPEECH,
GEO_MOONBALL, GEO_PYRAMID, GEO_PYRAMIDNEW, GEO_PYRAMIDFLOOR,
GEO_PYRAMIDWALL, GEO_PYRAMIDDOOR, GEO_PYRAMIDPILLAR, GEO_SPACESHIP,
GEO_PLANEBODY, GEO_PLANEWING, GEO_PLANEROCKET, GEO_POTATO,
GEO_PICKAXE, GEO_GUN, GEO_SWORD, GEO_RMSMALL,
GEO_RMMEDIUM, GEO_RMBIG, GEO_EXPLOSION, GEO_BULLETSKIN,
NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1ENABLED, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION,
U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION,
U_LIGHT2_COLOR, U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL,
U_LIGHT2_KQ, U_LIGHT2ENABLED, U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION,
U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT3_POSITION,
U_LIGHT3_COLOR, U_LIGHT3_POWER, U_LIGHT3_KC, U_LIGHT3_KL,
U_LIGHT3_KQ, U_LIGHT3ENABLED, U_LIGHT3_TYPE, U_LIGHT3_SPOTDIRECTION,
U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Mesh rendering function.
void UpdateMenu ()
void RenderSkybox ()
Renders skybox with rotation and scaling done.
void RenderText (Mesh *mesh, std::string text, Color color)
Text rendering function.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Text on screen rendering function.
void RenderQuadOnScreen (Mesh *mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z)
Renders meshlist/obj on screen.
void Dialogue (string filename)
Text pushed in array.
float checkNear (Camera3 camera, Vector3 rhs)
Camera position and item distance.
void Enemy_Rendering ()
Rendering Enemy In this scene.
void Enemy_Updating (float dt)
Updating Enemy In this scene.
void ObjectsHolding (Mesh *mesh, float size)
hold objects or parts
void Map_Reading ()
Reading map form Txt file for this scene.
void Map_Rendering ()
Rendering map based on Txt file for this scene.
void Character_Movement (float dt)
Platers controls for this scene.
void Plane_Rendering ()
Private Attributes
unsigned m_vertexArrayID
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
NPC npc
bool robot1moved = false
bool robot1rotate = false
float robot1rotation = 0
float xtranslate
float ytranslate
int parts = 0
Mesh * meshList [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
float LSPEED = 10.f
float moveSkyBoxZ = 91.f
float moveSkyBoxX = 0.f
Light light [8]
float potatoRotate
string new_line
Camera3 camera
vector< string > my_arr
vector< Bullet * > bullet_arr
Vector3 RobotPosition1
double b_coolDown
double b_coolDownLimit
bool startCoolDdown
int b_Ammo
float storyPosition
bool storyDismiss
bool storyShow
string story
float deltaTime
Bullet bullet
int Died_Time = 0
Enemy enemy [5]
float throwingdown = 0
float throwingforward = 0
float throwup = 0
Vector3 newcameraposition = (0, 0, 0)
Vector3 oldcameraposition = (0, 0, 0)
bool throwbomb = false
bool thrown = false
bool toggle = false
bool cam1 = false
bool movement = true
bool pickupegg1 = false
bool pickupegg2 = false
bool pickupegg3 = false
bool pickupegg4 = false
bool pickupegg5 = false
bool pickupwing = false
bool pickuprocket = false
float followx = 0
float followy = 0
bool fixwing = false
bool fixrocket = false
float coolDownTime
string shop
bool doorinteract = true
float JumpTime
float PressTime
Mouse mouse
CollisionDetector detectCollision
bool On_Plane = false
float Speed = 0
Position Plane
Animation animation
float swordRotation
float pickAxeRotation
float gunRotation
float gunTranslation
float swordTranslation
float pickAxeTranslation
bool playSlashingAnimation
bool playShootingAnimation
bool playMiningAnimation
bool usingSword
bool usingGun
bool usingPickAxe
int weaponChoice
int gun
int sword
int pickaxe
Sound sound
rawMaterial oreMaterial_arr [3]
double rm_coolDown
double rm_coolDownLimit
bool startRMcoolDown
Detailed Description
Class objects, meshes to render, booleans, floats and strings.
Class SceneWin:
Definition at line 47 of file Scene2.h.
Member Enumeration Documentation
enum Scene2::GEOMETRY_TYPE private
Enumerator
GEO_REF_AXES
GEO_REF_QUAD
GEO_QUAD
GEO_ENEMY
GEO_CROSSHAIR
GEO_LEFT1
GEO_RIGHT1
GEO_TOP1
GEO_BOTTOM1
GEO_FRONT1
GEO_BACK1
GEO_STAR
GEO_STORY1
GEO_TEXT
GEO_AMMOICON
GEO_GOLDICON
GEO_EGGICON
GEO_BOMBICON
GEO_OREICON
GEO_GUNICON
GEO_PICKAXEICON
GEO_SWORDICON
GEO_BOMB
GEO_CCTV
GEO_EGG
GEO_BAG
GEO_RING
GEO_PRISM
GEO_SPEHERE
GEO_BULLET
GEO_ROBOTH
GEO_ROBOTB
GEO_ROBOT
GEO_ROBOT1
GEO_ROBOT2
GEO_SPEECH
GEO_MOONBALL
GEO_PYRAMID
GEO_PYRAMIDNEW
GEO_PYRAMIDFLOOR
GEO_PYRAMIDWALL
GEO_PYRAMIDDOOR
GEO_PYRAMIDPILLAR
GEO_SPACESHIP
GEO_PLANEBODY
GEO_PLANEWING
GEO_PLANEROCKET
GEO_POTATO
GEO_PICKAXE
GEO_GUN
GEO_SWORD
GEO_RMSMALL
GEO_RMMEDIUM
GEO_RMBIG
GEO_EXPLOSION
GEO_BULLETSKIN
NUM_GEOMETRY
Definition at line 49 of file Scene2.h.
enum Scene2::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1ENABLED
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2ENABLED
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_LIGHT3_POSITION
U_LIGHT3_COLOR
U_LIGHT3_POWER
U_LIGHT3_KC
U_LIGHT3_KL
U_LIGHT3_KQ
U_LIGHT3ENABLED
U_LIGHT3_TYPE
U_LIGHT3_SPOTDIRECTION
U_LIGHT3_COSCUTOFF
U_LIGHT3_COSINNER
U_LIGHT3_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 130 of file Scene2.h.
Constructor & Destructor Documentation
Scene2::Scene2 ()
Default constructor.
Exceptions
None
Returns
None
Definition at line 54 of file Scene2.cpp.
Scene2::~Scene2 ()
Default destructor.
Exceptions
None
Returns
None
Definition at line 66 of file Scene2.cpp.
Member Function Documentation
void Scene2::Character_Movement (float dt) private
Platers controls for this scene.
Exceptions
None
Returns
None
Definition at line 1808 of file Scene2.cpp.
References camera, Camera3::cameraRotate, Camera3::cameraSpeed, checkNear(), NPC::DOT::Collision, Vector3::Cross(), Camera3::defaultUp, Math::DegreeToRadian(), NPC::door, doorinteract, enemy, followx, followy, SharedData::gameState, SharedData::GetInstance(), Application::IsKeyPressed(), light, Map, Camera3::maxCameraX, Camera3::maxX, Camera3::maxZ, Camera3::minX, Camera3::minZ, npc, NPC::DOT::Nposition, On_Plane, Plane, Camera::position, Light::position, Light::power, Camera3::Reset(), SharedData::SCENE2, Vector3::Set(), Size, Speed, SharedData::stateCheck, Camera::target, Camera::up, Camera3::view, VtoP(), Position::x, Vector3::x, X_Displacement, Position::y, Vector3::y, Position::z, Vector3::z, and Z_Displacement.
Referenced by Update().
float Scene2::checkNear (Camera3 camera, Vector3 rhs) private
Camera position and item distance.
Parameters
camera Passes in camera
rhs Object position
Exceptions
None
Returns
the distance between objects
Definition at line 476 of file Scene2.cpp.
References Camera::position, Vector3::x, and Vector3::z.
Referenced by Character_Movement().
void Scene2::Dialogue (string filename) private
Text pushed in array.
Parameters
filename Passes in the text file to be pushed into array
Exceptions
None
Returns
None
Definition at line 875 of file Scene2.cpp.
References my_arr, and new_line.
Referenced by Init().
void Scene2::Enemy_Rendering () private
Rendering Enemy In this scene.
Exceptions
None
Returns
None
Definition at line 1707 of file Scene2.cpp.
References enemy, GEO_ENEMY, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), Enemy::Return_Position(), MS::Scale(), MS::Translate(), Position::x, and Position::z.
Referenced by Render().
void Scene2::Enemy_Updating (float dt) private
Updating Enemy In this scene.
Exceptions
None
Returns
None
Definition at line 1689 of file Scene2.cpp.
References camera, enemy, Enemy::Enemy_movement(), Map, Camera::position, Size, Vector3::x, X_Displacement, Vector3::y, Vector3::z, and Z_Displacement.
Referenced by Update().
void Scene2::Exit () virtual
Exit and delete scene.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 1674 of file Scene2.cpp.
References m_programID, and m_vertexArrayID.
void Scene2::Init () virtual
Initializes for 2nd scene.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 78 of file Scene2.cpp.
References b_coolDown, b_coolDownLimit, camera, Camera3::cameraRotate, NPC::DOT::canGoThrough, NPC::DOT::Collision, Light::color, Light::cosCutOff, Light::cosInner, Math::DegreeToRadian(), Dialogue(), NPC::door, NPC::egg1, NPC::egg2, NPC::egg3, NPC::egg4, NPC::egg5, Light::exponent, SharedData::gameScene, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRepeatQuad(), MeshBuilder::GenerateText(), GEO_AMMOICON, GEO_BACK1, GEO_BOMB, GEO_BOMBICON, GEO_BOTTOM1, GEO_BULLETSKIN, GEO_CCTV, GEO_CROSSHAIR, GEO_EGGICON, GEO_ENEMY, GEO_EXPLOSION, GEO_FRONT1, GEO_GOLDICON, GEO_GUN, GEO_GUNICON, GEO_LEFT1, GEO_MOONBALL, GEO_OREICON, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_POTATO, GEO_PRISM, GEO_PYRAMID, GEO_PYRAMIDDOOR, GEO_PYRAMIDFLOOR, GEO_PYRAMIDNEW, GEO_PYRAMIDPILLAR, GEO_PYRAMIDWALL, GEO_QUAD, GEO_REF_AXES, GEO_RIGHT1, GEO_RING, GEO_RMBIG, GEO_RMMEDIUM, GEO_RMSMALL, GEO_ROBOT, GEO_ROBOT1, GEO_ROBOTB, GEO_ROBOTH, GEO_SPACESHIP, GEO_SPEECH, GEO_SPEHERE, GEO_STORY1, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, GEO_TOP1, SharedData::GetInstance(), gun, gunRotation, gunTranslation, Camera3::Init(), JumpTime, Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Map_Reading(), Mesh::material, meshList, npc, NPC::DOT::Nposition, On_Plane, oreMaterial_arr, pickAxeRotation, pickAxeTranslation, Plane, Sound::playMusic(), rawMaterial::pos, Light::position, potatoRotate, Light::power, PressTime, projectionStack, rm_coolDown, rm_coolDownLimit, NPC::robot1, NPC::robot2, NPC::robot3, Position::Set(), Component::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), sound, NPC::spaceShip, Light::spotDirection, startCoolDdown, startRMcoolDown, storyPosition, storyShow, swordRotation, swordTranslation, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POSITION, U_LIGHT2_POWER, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_TYPE, U_LIGHT3_COLOR, U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT, U_LIGHT3_KC, U_LIGHT3_KL, U_LIGHT3_KQ, U_LIGHT3_POSITION, U_LIGHT3_POWER, U_LIGHT3_SPOTDIRECTION, U_LIGHT3_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, usingGun, usingPickAxe, usingSword, and weaponChoice.
void Scene2::Map_Reading () private
Reading map form Txt file for this scene.
Exceptions
None
Returns
None
Definition at line 1729 of file Scene2.cpp.
References Map.
Referenced by Init().
void Scene2::Map_Rendering () private
Rendering map based on Txt file for this scene.
Exceptions
None
Returns
None
Definition at line 1757 of file Scene2.cpp.
References GEO_POTATO, GEO_PYRAMIDNEW, GEO_PYRAMIDPILLAR, GEO_PYRAMIDWALL, Map, meshList, modelStack, MS::PopMatrix(), potatoRotate, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Size, MS::Translate(), X_Displacement, and Z_Displacement.
Referenced by Render().
void Scene2::ObjectsHolding (Mesh * mesh, float size) private
hold objects or parts
Parameters
mesh Takes in which mesh to render out
size Scale of the mesh to render out
Exceptions
None
Returns
None
Definition at line 2068 of file Scene2.cpp.
References camera, followx, followy, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
void Scene2::Plane_Rendering () private
Definition at line 2087 of file Scene2.cpp.
References GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, meshList, modelStack, Plane, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Position::x, Position::y, and Position::z.
Referenced by Render().
void Scene2::Render () virtual
Main rendering function.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 1149 of file Scene2.cpp.
References SharedData::bomb, SharedData::bullet, bullet_arr, camera, NPC::DOT::canInteract, CollisionDetector::collideByDist(), deltaTime, detectCollision, NPC::dialogue, NPC::dialoguePlus, Died_Time, NPC::door, doorinteract, SharedData::egg, NPC::egg1, NPC::egg2, NPC::egg3, NPC::egg4, NPC::egg5, enemy, Enemy_Rendering(), followx, followy, GEO_AMMOICON, GEO_BOMBICON, GEO_BULLETSKIN, GEO_CCTV, GEO_CROSSHAIR, GEO_EGGICON, GEO_GOLDICON, GEO_GUN, GEO_GUNICON, GEO_MOONBALL, GEO_OREICON, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PRISM, GEO_PYRAMIDDOOR, GEO_PYRAMIDFLOOR, GEO_QUAD, GEO_RING, GEO_ROBOT, GEO_ROBOT1, GEO_ROBOTB, GEO_ROBOTH, GEO_SPACESHIP, GEO_SPEECH, GEO_SPEHERE, GEO_STORY1, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, SharedData::GetInstance(), SharedData::gold, gun, gunRotation, gunTranslation, NPC::interactDia, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, Map_Rendering(), meshList, SharedData::mineral, modelStack, my_arr, npc, NPC::DOT::Nposition, On_Plane, oreMaterial_arr, pickaxe, pickAxeRotation, pickAxeTranslation, pickupegg1, pickupegg2, pickupegg3, pickupegg4, pickupegg5, Plane, Plane_Rendering(), MS::PopMatrix(), rawMaterial::pos, Camera::position, Light::position, potatoRotate, MS::PushMatrix(), SharedData::INVENTORY::quantity, RenderMesh(), RenderQuadOnScreen(), RenderSkybox(), RenderTextOnScreen(), Camera3::Reset(), NPC::DOT::robot, NPC::robot1, robot1rotation, NPC::robot2, NPC::robot3, MS::Rotate(), MS::Scale(), shop, NPC::spaceShip, NPC::speech, Light::spotDirection, storyDismiss, storyPosition, sword, swordRotation, swordTranslation, Camera::target, throwup, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, U_LIGHT2_POSITION, U_LIGHT2_SPOTDIRECTION, U_LIGHT3_POSITION, U_LIGHT3_SPOTDIRECTION, Camera::up, viewStack, VtoP(), Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void Scene2::RenderMesh (Mesh * mesh, bool enableLight) private
Mesh rendering function.
Exceptions
None
Returns
None
Definition at line 895 of file Scene2.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, Lighting9, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Enemy_Rendering(), Map_Rendering(), ObjectsHolding(), Plane_Rendering(), Render(), RenderQuadOnScreen(), and RenderSkybox().
void Scene2::RenderQuadOnScreen (Mesh * mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z) private
Renders meshlist/obj on screen.
Parameters
mesh The mesh to render
size Scale of the mesh to render
x,y and z Position of the mesh to render
rotate,rx,ry and rz Rotation of mesh to render
z Z layering
Exceptions
None
Returns
None
Definition at line 1053 of file Scene2.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void Scene2::RenderSkybox () private
Renders skybox with rotation and scaling done.
Exceptions
None
Returns
None
Definition at line 1081 of file Scene2.cpp.
References GEO_BACK1, GEO_BOTTOM1, GEO_FRONT1, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), SBSCALE1, MS::Scale(), and MS::Translate().
Referenced by Render().
void Scene2::RenderText (Mesh * mesh, std::string text, Color color) private
Text rendering function.
Exceptions
None
Returns
None
Definition at line 944 of file Scene2.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void Scene2::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Text on screen rendering function.
Exceptions
None
Returns
None
Definition at line 979 of file Scene2.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, viewStack, xtranslate, and ytranslate.
Referenced by Render().
void Scene2::Update (double dt) virtual
Updates the scene every frame (Animation/booleans/music etc)
Exceptions
None
Returns
None
when untoggle below runs agains
Implements Scene.
Definition at line 490 of file Scene2.cpp.
References animation, b_coolDown, b_coolDownLimit, SharedData::bullet, bullet, bullet_arr, cam1, camera, NPC::DOT::canGoThrough, NPC::DOT::canInteract, Character_Movement(), CollisionDetector::collideByDist(), NPC::DOT::Collision, coolDownTime, deltaTime, detectCollision, NPC::dialoguePlus, NPC::door, NPC::Door(), SharedData::egg, NPC::egg1, NPC::egg2, NPC::egg3, NPC::egg4, NPC::egg5, enemy, Enemy_Updating(), followx, followy, SharedData::gameState, GEO_RMBIG, GEO_RMMEDIUM, GEO_RMSMALL, SharedData::GetInstance(), gun, gunTranslation, rawMaterial::hp, NPC::interactDia, rawMaterial::isAlive, Application::IsKeyPressed(), meshList, Animation::Mine(), SharedData::mineral, mouse, Mouse::MouseUpdate(), Animation::moveGun(), movement, Animation::moveSword(), my_arr, newcameraposition, npc, NPC::NPCmovement(), NPC::NPCmovement2(), NPC::DOT::Nposition, oldcameraposition, On_Plane, oreMaterial_arr, pickaxe, pickAxeRotation, pickAxeTranslation, pickupegg1, pickupegg2, pickupegg3, pickupegg4, pickupegg5, playMiningAnimation, Sound::playSE(), playShootingAnimation, playSlashingAnimation, rawMaterial::pos, Camera::position, potatoRotate, SharedData::INVENTORY::quantity, rm_coolDown, rm_coolDownLimit, NPC::DOT::robot, NPC::robot1, robot1rotation, NPC::robot3, NPC::Scene1(), rawMaterial::shape, Animation::Shoot(), SharedData::SHOP, Animation::Slash(), sound, NPC::spaceShip, startCoolDdown, startRMcoolDown, SharedData::stateCheck, Sound::stopMusic(), storyDismiss, storyPosition, storyShow, sword, CollisionDetector::swordCollision(), swordRotation, swordTranslation, Mesh::textureID, toggle, usingGun, usingPickAxe, usingSword, weaponChoice, Vector3::y, and Vector3::z.
void Scene2::UpdateMenu () private
Field Documentation
Animation Scene2::animation private
Definition at line 325 of file Scene2.h.
Referenced by Update().
int Scene2::b_Ammo private
Definition at line 264 of file Scene2.h.
double Scene2::b_coolDown private
Definition at line 261 of file Scene2.h.
Referenced by Init(), and Update().
double Scene2::b_coolDownLimit private
Definition at line 262 of file Scene2.h.
Referenced by Init(), and Update().
Bullet Scene2::bullet private
Definition at line 273 of file Scene2.h.
Referenced by Update().
vector<Bullet*> Scene2::bullet_arr private
Definition at line 259 of file Scene2.h.
Referenced by Render(), and Update().
bool Scene2::cam1 = false private
Definition at line 290 of file Scene2.h.
Referenced by Update().
Camera3 Scene2::camera private
Definition at line 256 of file Scene2.h.
Referenced by Character_Movement(), Enemy_Updating(), Init(), ObjectsHolding(), Render(), and Update().
float Scene2::coolDownTime private
Definition at line 305 of file Scene2.h.
Referenced by Update().
float Scene2::deltaTime private
Definition at line 272 of file Scene2.h.
Referenced by Render(), and Update().
CollisionDetector Scene2::detectCollision private
Definition at line 318 of file Scene2.h.
Referenced by Render(), and Update().
int Scene2::Died_Time = 0 private
Definition at line 275 of file Scene2.h.
Referenced by Render().
bool Scene2::doorinteract = true private
Definition at line 307 of file Scene2.h.
Referenced by Character_Movement(), and Render().
Enemy Scene2::enemy[5] private
Definition at line 276 of file Scene2.h.
Referenced by Character_Movement(), Enemy_Rendering(), Enemy_Updating(), Render(), and Update().
bool Scene2::fixrocket = false private
Definition at line 304 of file Scene2.h.
bool Scene2::fixwing = false private
Definition at line 303 of file Scene2.h.
float Scene2::followx = 0 private
Definition at line 301 of file Scene2.h.
Referenced by Character_Movement(), ObjectsHolding(), Render(), and Update().
float Scene2::followy = 0 private
Definition at line 302 of file Scene2.h.
Referenced by Character_Movement(), ObjectsHolding(), Render(), and Update().
int Scene2::gun private
Definition at line 343 of file Scene2.h.
Referenced by Init(), Render(), and Update().
float Scene2::gunRotation private
Definition at line 328 of file Scene2.h.
Referenced by Init(), and Render().
float Scene2::gunTranslation private
Definition at line 330 of file Scene2.h.
Referenced by Init(), Render(), and Update().
float Scene2::JumpTime private
Definition at line 314 of file Scene2.h.
Referenced by Init().
Light Scene2::light[8] private
Definition at line 243 of file Scene2.h.
Referenced by Character_Movement(), Init(), and Render().
float Scene2::LSPEED = 10.f private
Definition at line 239 of file Scene2.h.
unsigned Scene2::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 222 of file Scene2.h.
unsigned Scene2::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 220 of file Scene2.h.
unsigned Scene2::m_parameters[U_TOTAL] private
Definition at line 224 of file Scene2.h.
Referenced by Init(), Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned Scene2::m_programID private
Definition at line 223 of file Scene2.h.
Referenced by Exit(), and Init().
unsigned Scene2::m_vertexArrayID private
Definition at line 219 of file Scene2.h.
Referenced by Exit(), and Init().
unsigned Scene2::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 221 of file Scene2.h.
char Scene2::Map[20][20]
Definition at line 204 of file Scene2.h.
Referenced by Character_Movement(), Enemy_Updating(), Map_Reading(), and Map_Rendering().
Mesh* Scene2::meshList[NUM_GEOMETRY] private
Definition at line 236 of file Scene2.h.
Referenced by Enemy_Rendering(), Init(), Map_Rendering(), Plane_Rendering(), Render(), RenderSkybox(), and Update().
MS Scene2::modelStack private
Definition at line 238 of file Scene2.h.
Referenced by Enemy_Rendering(), Map_Rendering(), ObjectsHolding(), Plane_Rendering(), Render(), RenderMesh(), RenderQuadOnScreen(), RenderSkybox(), RenderText(), and RenderTextOnScreen().
Mouse Scene2::mouse private
Definition at line 317 of file Scene2.h.
Referenced by Update().
bool Scene2::movement = true private
Definition at line 291 of file Scene2.h.
Referenced by Update().
float Scene2::moveSkyBoxX = 0.f private
Definition at line 241 of file Scene2.h.
float Scene2::moveSkyBoxZ = 91.f private
Definition at line 240 of file Scene2.h.
vector<string> Scene2::my_arr private
Definition at line 258 of file Scene2.h.
Referenced by Dialogue(), Render(), and Update().
string Scene2::new_line private
Definition at line 251 of file Scene2.h.
Referenced by Dialogue().
Vector3 Scene2::newcameraposition = (0, 0, 0) private
Definition at line 285 of file Scene2.h.
Referenced by Update().
NPC Scene2::npc private
Definition at line 227 of file Scene2.h.
Referenced by Character_Movement(), Init(), Render(), and Update().
Vector3 Scene2::oldcameraposition = (0, 0, 0) private
Definition at line 286 of file Scene2.h.
Referenced by Update().
bool Scene2::On_Plane = false private
Definition at line 320 of file Scene2.h.
Referenced by Character_Movement(), Init(), Render(), and Update().
rawMaterial Scene2::oreMaterial_arr[3] private
Definition at line 349 of file Scene2.h.
Referenced by Init(), Render(), and Update().
int Scene2::parts = 0 private
Definition at line 233 of file Scene2.h.
int Scene2::pickaxe private
Definition at line 345 of file Scene2.h.
Referenced by Render(), and Update().
float Scene2::pickAxeRotation private
Definition at line 327 of file Scene2.h.
Referenced by Init(), Render(), and Update().
float Scene2::pickAxeTranslation private
Definition at line 332 of file Scene2.h.
Referenced by Init(), Render(), and Update().
bool Scene2::pickupegg1 = false private
Definition at line 292 of file Scene2.h.
Referenced by Render(), and Update().
bool Scene2::pickupegg2 = false private
Definition at line 293 of file Scene2.h.
Referenced by Render(), and Update().
bool Scene2::pickupegg3 = false private
Definition at line 294 of file Scene2.h.
Referenced by Render(), and Update().
bool Scene2::pickupegg4 = false private
Definition at line 295 of file Scene2.h.
Referenced by Render(), and Update().
bool Scene2::pickupegg5 = false private
Definition at line 296 of file Scene2.h.
Referenced by Render(), and Update().
bool Scene2::pickuprocket = false private
Definition at line 300 of file Scene2.h.
bool Scene2::pickupwing = false private
Definition at line 299 of file Scene2.h.
Position Scene2::Plane private
Definition at line 322 of file Scene2.h.
Referenced by Character_Movement(), Init(), Plane_Rendering(), and Render().
bool Scene2::playMiningAnimation private
Definition at line 336 of file Scene2.h.
Referenced by Update().
bool Scene2::playShootingAnimation private
Definition at line 335 of file Scene2.h.
Referenced by Update().
bool Scene2::playSlashingAnimation private
Definition at line 334 of file Scene2.h.
Referenced by Update().
float Scene2::potatoRotate private
Definition at line 244 of file Scene2.h.
Referenced by Init(), Map_Rendering(), Render(), and Update().
float Scene2::PressTime private
Definition at line 315 of file Scene2.h.
Referenced by Init().
MS Scene2::projectionStack private
Definition at line 238 of file Scene2.h.
Referenced by Init(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
double Scene2::rm_coolDown private
Definition at line 350 of file Scene2.h.
Referenced by Init(), and Update().
double Scene2::rm_coolDownLimit private
Definition at line 351 of file Scene2.h.
Referenced by Init(), and Update().
bool Scene2::robot1moved = false private
Definition at line 228 of file Scene2.h.
bool Scene2::robot1rotate = false private
Definition at line 229 of file Scene2.h.
float Scene2::robot1rotation = 0 private
Definition at line 230 of file Scene2.h.
Referenced by Render(), and Update().
Vector3 Scene2::RobotPosition1 private
Definition at line 260 of file Scene2.h.
string Scene2::shop private
Definition at line 306 of file Scene2.h.
Referenced by Render().
float Scene2::Size = 15
Definition at line 205 of file Scene2.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
Sound Scene2::sound private
Definition at line 347 of file Scene2.h.
Referenced by Init(), and Update().
float Scene2::Speed = 0 private
Definition at line 321 of file Scene2.h.
Referenced by Character_Movement().
bool Scene2::startCoolDdown private
Definition at line 263 of file Scene2.h.
Referenced by Init(), and Update().
bool Scene2::startRMcoolDown private
Definition at line 352 of file Scene2.h.
Referenced by Init(), and Update().
string Scene2::story private
Definition at line 270 of file Scene2.h.
bool Scene2::storyDismiss private
Definition at line 268 of file Scene2.h.
Referenced by Render(), and Update().
float Scene2::storyPosition private
Definition at line 267 of file Scene2.h.
Referenced by Init(), Render(), and Update().
bool Scene2::storyShow private
Definition at line 269 of file Scene2.h.
Referenced by Init(), and Update().
int Scene2::sword private
Definition at line 344 of file Scene2.h.
Referenced by Render(), and Update().
float Scene2::swordRotation private
Definition at line 326 of file Scene2.h.
Referenced by Init(), Render(), and Update().
float Scene2::swordTranslation private
Definition at line 331 of file Scene2.h.
Referenced by Init(), Render(), and Update().
bool Scene2::throwbomb = false private
Definition at line 287 of file Scene2.h.
float Scene2::throwingdown = 0 private
Definition at line 282 of file Scene2.h.
float Scene2::throwingforward = 0 private
Definition at line 283 of file Scene2.h.
bool Scene2::thrown = false private
Definition at line 288 of file Scene2.h.
float Scene2::throwup = 0 private
Definition at line 284 of file Scene2.h.
Referenced by Render().
bool Scene2::toggle = false private
Definition at line 289 of file Scene2.h.
Referenced by Update().
bool Scene2::usingGun private
Definition at line 339 of file Scene2.h.
Referenced by Init(), and Update().
bool Scene2::usingPickAxe private
Definition at line 340 of file Scene2.h.
Referenced by Init(), and Update().
bool Scene2::usingSword private
Definition at line 338 of file Scene2.h.
Referenced by Init(), and Update().
MS Scene2::viewStack private
Definition at line 238 of file Scene2.h.
Referenced by Render(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
int Scene2::weaponChoice private
Definition at line 341 of file Scene2.h.
Referenced by Init(), and Update().
float Scene2::X_Displacement = -100
Definition at line 207 of file Scene2.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
float Scene2::xtranslate private
Definition at line 231 of file Scene2.h.
Referenced by RenderTextOnScreen().
float Scene2::ytranslate private
Definition at line 232 of file Scene2.h.
Referenced by RenderTextOnScreen().
float Scene2::Z_Displacement = 0
Definition at line 206 of file Scene2.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
The documentation for this class was generated from the following files:
MyGraphics/Source/Scene2.h
MyGraphics/Source/Scene2.cpp