My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Static Public Member Functions
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateQuad (const std::string &meshName, Color color, float lengthX, float lengthY)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateRepeatQuad (const std::string &meshName, Color color, float lengthX, float lengthY, int textCoord)
static Mesh * GenerateCube (const std::string &meshName, Color color, float lengthX, float lengthY, float lengthZ)
static Mesh * GenerateCircle (const std::string &meshName, Color color, float lengthX, float lengthZ)
static Mesh * GenerateCircles (const std::string &meshName, Color color, unsigned numSlices)
static Mesh * GenerateHemisphere (const std::string &meshName, Color color, float lengthX, float lengthY, float lengthZ, float radius)
static Mesh * GenerateSphere (const std::string &meshName, Color color, float radius, float lengthX, float lengthY)
static Mesh * GenerateSpheres (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices, float lengthX=1, float lengthY=1, float lengthZ=1)
static Mesh * GenerateConeHem (const std::string &meshName, Color color, unsigned numStacks=18, unsigned numSlices=36)
static Mesh * GenerateCylinder (const std::string &meshName, Color color, unsigned numSlices)
static Mesh * GenerateCone (const std::string &meshName, Color color, unsigned numSlices)
static Mesh * GenerateRing (const std::string &meshName, Color color, float innerRadius, float outerRadius)
static Mesh * GenerateRings (const std::string &meshName, Color color, float innerRadius, unsigned numSlices)
static Mesh * GenerateTorus (const std::string &meshName, Color color, float outerRadius, float innerRadius, unsigned numSlices, unsigned numStacks)
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
static Mesh * GenerateCone2 (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices, float lengthX=1, float lengthY=1, float lengthZ=1)
static Mesh * GenerateCylinder2 (const std::string &meshName, Color color, float height, float numStack, float radius, float lengthX=1, float lengthY=1, float lengthZ=1)
static Mesh * GenerateCones2 (const std::string &meshName, Color color, unsigned numSlices, float lengthX=1, float lengthY=1, float lengthZ=1)
static Mesh * GenerateCubes2 (const std::string &meshName, Color color, float lengthX=1, float lengthY=1, float lengthZ=1)
static Mesh * GenerateHemispheres2 (const std::string &meshName, Color color, unsigned numStacks, unsigned numSlices, float lengthX=1, float lengthY=1, float lengthZ=1)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 13 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 23 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), and Mesh::vertexBuffer.
Referenced by Shop::Init(), Scene3::Init(), and Scene2::Init().
static Mesh* MeshBuilder::GenerateCircle (const std::string & meshName, Color color, float lengthX, float lengthZ) static
static Mesh* MeshBuilder::GenerateCircles (const std::string & meshName, Color color, unsigned numSlices) static
static Mesh* MeshBuilder::GenerateCone (const std::string & meshName, Color color, unsigned numSlices) static
static Mesh* MeshBuilder::GenerateCone2 (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices, float lengthX = 1, float lengthY = 1, float lengthZ = 1) static
static Mesh* MeshBuilder::GenerateConeHem (const std::string & meshName, Color color, unsigned numStacks = 18, unsigned numSlices = 36) static
static Mesh* MeshBuilder::GenerateCones2 (const std::string & meshName, Color color, unsigned numSlices, float lengthX = 1, float lengthY = 1, float lengthZ = 1) static
static Mesh* MeshBuilder::GenerateCube (const std::string & meshName, Color color, float lengthX, float lengthY, float lengthZ) static
static Mesh* MeshBuilder::GenerateCubes2 (const std::string & meshName, Color color, float lengthX = 1, float lengthY = 1, float lengthZ = 1) static
static Mesh* MeshBuilder::GenerateCylinder (const std::string & meshName, Color color, unsigned numSlices) static
static Mesh* MeshBuilder::GenerateCylinder2 (const std::string & meshName, Color color, float height, float numStack, float radius, float lengthX = 1, float lengthY = 1, float lengthZ = 1) static
static Mesh* MeshBuilder::GenerateHemisphere (const std::string & meshName, Color color, float lengthX, float lengthY, float lengthZ, float radius) static
static Mesh* MeshBuilder::GenerateHemispheres2 (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices, float lengthX = 1, float lengthY = 1, float lengthZ = 1) static
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 398 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by SceneMenu::Init(), Cutscene::Init(), Shop::Init(), StartCutScene::Init(), Scene3::Init(), SP2::Init(), Scene2::Init(), and rawMaterial::rawMaterial().
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color, float lengthX, float lengthY) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 107 of file MeshBuilder.cpp.
References Color::b, Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Color::g, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Color::r, Position::Set(), Color::Set(), Vector3::Set(), TexCoord::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SceneWin::Init(), SceneMenu::Init(), Cutscene::Init(), Shop::Init(), StartCutScene::Init(), Scene3::Init(), SP2::Init(), and Scene2::Init().
Mesh * MeshBuilder::GenerateRepeatQuad (const std::string & meshName, Color color, float lengthX, float lengthY, int textCoord) static
Definition at line 174 of file MeshBuilder.cpp.
References Color::b, Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Color::g, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Color::r, Position::Set(), Color::Set(), Vector3::Set(), TexCoord::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by Cutscene::Init(), Shop::Init(), StartCutScene::Init(), Scene3::Init(), SP2::Init(), and Scene2::Init().
static Mesh* MeshBuilder::GenerateRing (const std::string & meshName, Color color, float innerRadius, float outerRadius) static
static Mesh* MeshBuilder::GenerateRings (const std::string & meshName, Color color, float innerRadius, unsigned numSlices) static
static Mesh* MeshBuilder::GenerateSphere (const std::string & meshName, Color color, float radius, float lengthX, float lengthY) static
Mesh * MeshBuilder::GenerateSpheres (const std::string & meshName, Color color, unsigned numStacks, unsigned numSlices, float lengthX = 1, float lengthY = 1, float lengthZ = 1) static
Definition at line 341 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), Mesh::vertexBuffer, Position::x, Position::y, and Position::z.
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 241 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), TexCoord::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by SceneWin::Init(), SceneMenu::Init(), Cutscene::Init(), Shop::Init(), StartCutScene::Init(), Scene3::Init(), SP2::Init(), and Scene2::Init().
static Mesh* MeshBuilder::GenerateTorus (const std::string & meshName, Color color, float outerRadius, float innerRadius, unsigned numSlices, unsigned numStacks) static
The documentation for this class was generated from the following files:
MyGraphics/Source/MeshBuilder.h
MyGraphics/Source/MeshBuilder.cpp