My Application: StartCutScene Class Reference
StartCutScene Class Reference
Scene rendering for starting cutscene.
#include <StartCutScene.h>
Public Member Functions
StartCutScene ()
Default constructor.
~StartCutScene ()
Default destructor.
virtual void Init ()
Initializes for this cut scene.
virtual void Update (double dt)
Updates the scene every frame.
virtual void Render ()
Main rendering.
virtual void Exit ()
Exits the game and cleanup.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
char Map [20][20]
float Size = 15
float Z_Displacement = 0
float X_Displacement = -100
Private Types
enum GEOMETRY_TYPE {
GEO_REF_AXES = 0, GEO_REF_QUAD, GEO_LIGHTBALL, GEO_QUAD,
GEO_BB8HEAD, GEO_BB8BODY, GEO_CROSSHAIR, GEO_THRUSTER,
GEO_LEFT1, GEO_RIGHT1, GEO_TOP1, GEO_BOTTOM1,
GEO_FRONT1, GEO_BACK1, GEO_STAR, GEO_STORY1,
GEO_TEXT, GEO_MOONBALL, GEO_PYRAMIDNEW, GEO_PYRAMIDWALL,
GEO_PYRAMIDPILLAR, GEO_SPACESHIP, GEO_PLANEBODY, GEO_PLANEWING,
GEO_PLANEROCKET, GEO_PYRAMIDFLOOR, GEO_PYRAMIDDOOR, GEO_EXPLOSION,
GEO_BULLETSKIN, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1ENABLED, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION,
U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION,
U_LIGHT2_COLOR, U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL,
U_LIGHT2_KQ, U_LIGHT2ENABLED, U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION,
U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT3_POSITION,
U_LIGHT3_COLOR, U_LIGHT3_POWER, U_LIGHT3_KC, U_LIGHT3_KL,
U_LIGHT3_KQ, U_LIGHT3ENABLED, U_LIGHT3_TYPE, U_LIGHT3_SPOTDIRECTION,
U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Renders mesh.
void UpdateMenu ()
void RenderSkybox ()
Renders skybox with scaling and rotation done.
void RenderText (Mesh *mesh, std::string text, Color color)
Renders text for scene.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Renders text on screen.
void RenderQuadOnScreen (Mesh *mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z)
void Map_Reading ()
void Map_Rendering ()
void Character_Movement (float dt)
Camera shaking, updating camera target.
Private Attributes
unsigned m_vertexArrayID
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Mesh * meshList [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
Light light [8]
Camera3 camera
Mouse mouse
Sound sound
float planePos =100
float planePos2 = 1000
int cameraShake
int randNum
bool blowUp
float explosionScale
float thrusterScale
Detailed Description
Scene rendering for starting cutscene.
Class StartCutScene:
Definition at line 36 of file StartCutScene.h.
Member Enumeration Documentation
enum StartCutScene::GEOMETRY_TYPE private
Enumerator
GEO_REF_AXES
GEO_REF_QUAD
GEO_LIGHTBALL
GEO_QUAD
GEO_BB8HEAD
GEO_BB8BODY
GEO_CROSSHAIR
GEO_THRUSTER
GEO_LEFT1
GEO_RIGHT1
GEO_TOP1
GEO_BOTTOM1
GEO_FRONT1
GEO_BACK1
GEO_STAR
GEO_STORY1
GEO_TEXT
GEO_MOONBALL
GEO_PYRAMIDNEW
GEO_PYRAMIDWALL
GEO_PYRAMIDPILLAR
GEO_SPACESHIP
GEO_PLANEBODY
GEO_PLANEWING
GEO_PLANEROCKET
GEO_PYRAMIDFLOOR
GEO_PYRAMIDDOOR
GEO_EXPLOSION
GEO_BULLETSKIN
NUM_GEOMETRY
Definition at line 38 of file StartCutScene.h.
enum StartCutScene::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1ENABLED
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2ENABLED
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_LIGHT3_POSITION
U_LIGHT3_COLOR
U_LIGHT3_POWER
U_LIGHT3_KC
U_LIGHT3_KL
U_LIGHT3_KQ
U_LIGHT3ENABLED
U_LIGHT3_TYPE
U_LIGHT3_SPOTDIRECTION
U_LIGHT3_COSCUTOFF
U_LIGHT3_COSINNER
U_LIGHT3_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 79 of file StartCutScene.h.
Constructor & Destructor Documentation
StartCutScene::StartCutScene ()
Default constructor.
Exceptions
None
Returns
None
Definition at line 27 of file StartCutScene.cpp.
StartCutScene::~StartCutScene ()
Default destructor.
Exceptions
None
Returns
None
Definition at line 39 of file StartCutScene.cpp.
Member Function Documentation
void StartCutScene::Character_Movement (float dt) private
Camera shaking, updating camera target.
Exceptions
None
Returns
None
Definition at line 513 of file StartCutScene.cpp.
References camera, Camera3::cameraRotate, Vector3::Cross(), Camera3::defaultUp, Math::DegreeToRadian(), Camera::position, randNum, Camera::target, Camera::up, Camera3::view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void StartCutScene::Exit () virtual
Exits the game and cleanup.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 487 of file StartCutScene.cpp.
References m_programID, and m_vertexArrayID.
void StartCutScene::Init () virtual
Initializes for this cut scene.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 51 of file StartCutScene.cpp.
References camera, Camera3::cameraRotate, MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRepeatQuad(), MeshBuilder::GenerateText(), GEO_BACK1, GEO_BOTTOM1, GEO_EXPLOSION, GEO_FRONT1, GEO_LEFT1, GEO_MOONBALL, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_PYRAMIDNEW, GEO_QUAD, GEO_RIGHT1, GEO_TEXT, GEO_THRUSTER, GEO_TOP1, Camera3::Init(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, Sound::playSE(), projectionStack, Component::Set(), Mtx44::SetToPerspective(), sound, Mesh::textureID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_TEXT_COLOR, and U_TEXT_ENABLED.
void StartCutScene::Map_Reading () private
void StartCutScene::Map_Rendering () private
Definition at line 492 of file StartCutScene.cpp.
References camera, GEO_PYRAMIDNEW, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Scale(), Size, MS::Translate(), X_Displacement, Vector3::y, and Z_Displacement.
Referenced by Render().
void StartCutScene::Render () virtual
Main rendering.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 410 of file StartCutScene.cpp.
References blowUp, camera, explosionScale, GEO_EXPLOSION, GEO_MOONBALL, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_QUAD, GEO_TEXT, GEO_THRUSTER, MS::LoadIdentity(), MS::LookAt(), Map_Rendering(), meshList, modelStack, planePos, planePos2, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), RenderSkybox(), RenderTextOnScreen(), MS::Rotate(), MS::Scale(), Camera::target, thrusterScale, MS::Translate(), Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void StartCutScene::RenderMesh (Mesh * mesh, bool enableLight) private
Renders mesh.
Exceptions
None
Returns
None
Definition at line 202 of file StartCutScene.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, Lighting9, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Map_Rendering(), Render(), and RenderSkybox().
void StartCutScene::RenderQuadOnScreen (Mesh * mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z) private
void StartCutScene::RenderSkybox () private
Renders skybox with scaling and rotation done.
Exceptions
None
Returns
None
Definition at line 342 of file StartCutScene.cpp.
References GEO_BACK1, GEO_BOTTOM1, GEO_FRONT1, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), SBSCALE1, MS::Scale(), and MS::Translate().
Referenced by Render().
void StartCutScene::RenderText (Mesh * mesh, std::string text, Color color) private
Renders text for scene.
Exceptions
None
Returns
None
Definition at line 251 of file StartCutScene.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void StartCutScene::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Renders text on screen.
Exceptions
None
Returns
None
Definition at line 286 of file StartCutScene.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void StartCutScene::Update (double dt) virtual
Updates the scene every frame.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 164 of file StartCutScene.cpp.
References blowUp, Character_Movement(), explosionScale, SharedData::GAME, SharedData::gameState, SharedData::GetInstance(), planePos, planePos2, and SharedData::stateCheck.
void StartCutScene::UpdateMenu () private
Field Documentation
bool StartCutScene::blowUp private
Definition at line 198 of file StartCutScene.h.
Referenced by Render(), and Update().
Camera3 StartCutScene::camera private
Definition at line 185 of file StartCutScene.h.
Referenced by Character_Movement(), Init(), Map_Rendering(), and Render().
int StartCutScene::cameraShake private
Definition at line 196 of file StartCutScene.h.
float StartCutScene::explosionScale private
Definition at line 199 of file StartCutScene.h.
Referenced by Render(), and Update().
Light StartCutScene::light[8] private
Definition at line 178 of file StartCutScene.h.
unsigned StartCutScene::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 168 of file StartCutScene.h.
unsigned StartCutScene::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 166 of file StartCutScene.h.
unsigned StartCutScene::m_parameters[U_TOTAL] private
Definition at line 170 of file StartCutScene.h.
Referenced by Init(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned StartCutScene::m_programID private
Definition at line 169 of file StartCutScene.h.
Referenced by Exit(), and Init().
unsigned StartCutScene::m_vertexArrayID private
Definition at line 165 of file StartCutScene.h.
Referenced by Exit(), and Init().
unsigned StartCutScene::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 167 of file StartCutScene.h.
char StartCutScene::Map[20][20]
Definition at line 150 of file StartCutScene.h.
Mesh* StartCutScene::meshList[NUM_GEOMETRY] private
Definition at line 175 of file StartCutScene.h.
Referenced by Init(), Map_Rendering(), Render(), and RenderSkybox().
MS StartCutScene::modelStack private
Definition at line 177 of file StartCutScene.h.
Referenced by Map_Rendering(), Render(), RenderMesh(), RenderSkybox(), RenderText(), and RenderTextOnScreen().
Mouse StartCutScene::mouse private
Definition at line 192 of file StartCutScene.h.
float StartCutScene::planePos =100 private
Definition at line 194 of file StartCutScene.h.
Referenced by Render(), and Update().
float StartCutScene::planePos2 = 1000 private
Definition at line 195 of file StartCutScene.h.
Referenced by Render(), and Update().
MS StartCutScene::projectionStack private
Definition at line 177 of file StartCutScene.h.
Referenced by Init(), RenderMesh(), RenderText(), and RenderTextOnScreen().
int StartCutScene::randNum private
Definition at line 197 of file StartCutScene.h.
Referenced by Character_Movement().
float StartCutScene::Size = 15
Definition at line 151 of file StartCutScene.h.
Referenced by Map_Rendering().
Sound StartCutScene::sound private
Definition at line 193 of file StartCutScene.h.
Referenced by Init().
float StartCutScene::thrusterScale private
Definition at line 200 of file StartCutScene.h.
Referenced by Render().
MS StartCutScene::viewStack private
Definition at line 177 of file StartCutScene.h.
Referenced by Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
float StartCutScene::X_Displacement = -100
Definition at line 153 of file StartCutScene.h.
Referenced by Map_Rendering().
float StartCutScene::Z_Displacement = 0
Definition at line 152 of file StartCutScene.h.
Referenced by Map_Rendering().
The documentation for this class was generated from the following files:
MyGraphics/Source/StartCutScene.h
MyGraphics/Source/StartCutScene.cpp