My Application: Cutscene Class Reference
Cutscene Class Reference
Meshes/booleans/floats for rendering and animation.
#include <Cutscene.h>
Public Member Functions
Cutscene ()
Default constructor.
~Cutscene ()
Default destructor.
virtual void Init ()
Initializes for cutscene, meshes/floats/booleans.
virtual void Update (double dt)
Updates the scene every frame (Animation/booleans/music etc)
virtual void Render ()
The main render function for this scene, renders any text/meshes.
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
char Map [20][20]
float Size = 15
float Z_Displacement = 0
float X_Displacement = -100
Private Types
enum GEOMETRY_TYPE {
GEO_REF_AXES = 0, GEO_REF_QUAD, GEO_LIGHTBALL, GEO_QUAD,
GEO_THRUSTER, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1,
GEO_BOTTOM1, GEO_FRONT1, GEO_BACK1, GEO_STAR,
GEO_STORY1, GEO_TEXT, GEO_MOONBALL, GEO_PYRAMIDNEW,
GEO_PYRAMIDWALL, GEO_PYRAMIDPILLAR, GEO_SPACESHIP, GEO_PLANEBODY,
GEO_PLANEWING, GEO_PLANEROCKET, GEO_PYRAMIDFLOOR, GEO_PYRAMIDDOOR,
GEO_EXPLOSION, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Mesh rendering function.
void RenderSkybox ()
Renders the skybox on screen with rotation, scaling done.
void RenderText (Mesh *mesh, std::string text, Color color)
Renders text.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Renders text on screen.
void RenderQuadOnScreen (Mesh *mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z)
void Map_Reading ()
void Map_Rendering ()
void Character_Movement (float dt)
Random camera shaking when explosion happens.
Private Attributes
unsigned m_vertexArrayID
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Mesh * meshList [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
Camera3 camera
Sound sound
float planePos =-20
float planePos2 = 350
int cameraShake
int randNum
bool blowUp
float explosionScale
float thrusterScale
Detailed Description
Meshes/booleans/floats for rendering and animation.
Class Cutscene:
Definition at line 32 of file Cutscene.h.
Member Enumeration Documentation
enum Cutscene::GEOMETRY_TYPE private
Enumerator
GEO_REF_AXES
GEO_REF_QUAD
GEO_LIGHTBALL
GEO_QUAD
GEO_THRUSTER
GEO_LEFT1
GEO_RIGHT1
GEO_TOP1
GEO_BOTTOM1
GEO_FRONT1
GEO_BACK1
GEO_STAR
GEO_STORY1
GEO_TEXT
GEO_MOONBALL
GEO_PYRAMIDNEW
GEO_PYRAMIDWALL
GEO_PYRAMIDPILLAR
GEO_SPACESHIP
GEO_PLANEBODY
GEO_PLANEWING
GEO_PLANEROCKET
GEO_PYRAMIDFLOOR
GEO_PYRAMIDDOOR
GEO_EXPLOSION
NUM_GEOMETRY
Definition at line 34 of file Cutscene.h.
enum Cutscene::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 69 of file Cutscene.h.
Constructor & Destructor Documentation
Cutscene::Cutscene ()
Default constructor.
Exceptions
None
Returns
None
Definition at line 27 of file Cutscene.cpp.
Cutscene::~Cutscene ()
Default destructor.
Exceptions
None
Returns
None
Definition at line 39 of file Cutscene.cpp.
Member Function Documentation
void Cutscene::Character_Movement (float dt) private
Random camera shaking when explosion happens.
Exceptions
None
Returns
None
Definition at line 495 of file Cutscene.cpp.
References camera, Camera3::cameraRotate, Vector3::Cross(), Camera3::defaultUp, Math::DegreeToRadian(), Camera::position, randNum, Camera::target, Camera::up, Camera3::view, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Update().
void Cutscene::Exit () virtual
Implements Scene.
Definition at line 469 of file Cutscene.cpp.
References m_programID, and m_vertexArrayID.
void Cutscene::Init () virtual
Initializes for cutscene, meshes/floats/booleans.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 51 of file Cutscene.cpp.
References camera, Camera3::cameraRotate, MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRepeatQuad(), MeshBuilder::GenerateText(), GEO_BACK1, GEO_BOTTOM1, GEO_EXPLOSION, GEO_FRONT1, GEO_LEFT1, GEO_MOONBALL, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_PYRAMIDNEW, GEO_QUAD, GEO_RIGHT1, GEO_TEXT, GEO_THRUSTER, GEO_TOP1, Camera3::Init(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Mesh::material, meshList, planePos2, Sound::playMusic(), projectionStack, Component::Set(), Mtx44::SetToPerspective(), sound, Mesh::textureID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_TEXT_COLOR, and U_TEXT_ENABLED.
void Cutscene::Map_Reading () private
void Cutscene::Map_Rendering () private
Definition at line 474 of file Cutscene.cpp.
References camera, GEO_PYRAMIDNEW, meshList, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Scale(), Size, MS::Translate(), X_Displacement, Vector3::y, and Z_Displacement.
Referenced by Render().
void Cutscene::Render () virtual
The main render function for this scene, renders any text/meshes.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 402 of file Cutscene.cpp.
References blowUp, camera, explosionScale, GEO_EXPLOSION, GEO_MOONBALL, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_QUAD, GEO_THRUSTER, MS::LoadIdentity(), MS::LookAt(), Map_Rendering(), meshList, modelStack, planePos, planePos2, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), RenderSkybox(), MS::Rotate(), MS::Scale(), Camera::target, thrusterScale, MS::Translate(), Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void Cutscene::RenderMesh (Mesh * mesh, bool enableLight) private
Mesh rendering function.
Exceptions
None
Returns
None
Definition at line 212 of file Cutscene.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MODELVIEW, U_MVP, and viewStack.
Referenced by Map_Rendering(), Render(), and RenderSkybox().
void Cutscene::RenderQuadOnScreen (Mesh * mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z) private
void Cutscene::RenderSkybox () private
Renders the skybox on screen with rotation, scaling done.
Exceptions
None
Returns
None
Definition at line 334 of file Cutscene.cpp.
References GEO_BACK1, GEO_BOTTOM1, GEO_FRONT1, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), SBSCALE1, MS::Scale(), and MS::Translate().
Referenced by Render().
void Cutscene::RenderText (Mesh * mesh, std::string text, Color color) private
Renders text.
Exceptions
None
Returns
None
Definition at line 246 of file Cutscene.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void Cutscene::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Renders text on screen.
Exceptions
None
Returns
None
Definition at line 280 of file Cutscene.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void Cutscene::Update (double dt) virtual
Updates the scene every frame (Animation/booleans/music etc)
Exceptions
None
Returns
None
Implements Scene.
Definition at line 166 of file Cutscene.cpp.
References blowUp, camera, Camera3::cameraRotate, Character_Movement(), explosionScale, SharedData::gameState, SharedData::GetInstance(), Camera3::Init(), planePos, planePos2, randNum, sound, SharedData::stateCheck, Sound::stopMusic(), thrusterScale, and SharedData::WIN.
Field Documentation
bool Cutscene::blowUp private
Definition at line 130 of file Cutscene.h.
Referenced by Render(), and Update().
Camera3 Cutscene::camera private
Definition at line 119 of file Cutscene.h.
Referenced by Character_Movement(), Init(), Map_Rendering(), Render(), and Update().
int Cutscene::cameraShake private
Definition at line 128 of file Cutscene.h.
float Cutscene::explosionScale private
Definition at line 131 of file Cutscene.h.
Referenced by Render(), and Update().
unsigned Cutscene::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 105 of file Cutscene.h.
unsigned Cutscene::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 103 of file Cutscene.h.
unsigned Cutscene::m_parameters[U_TOTAL] private
Definition at line 107 of file Cutscene.h.
Referenced by Init(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned Cutscene::m_programID private
Definition at line 106 of file Cutscene.h.
Referenced by Exit(), and Init().
unsigned Cutscene::m_vertexArrayID private
Definition at line 102 of file Cutscene.h.
Referenced by Exit(), and Init().
unsigned Cutscene::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 104 of file Cutscene.h.
char Cutscene::Map[20][20]
Definition at line 87 of file Cutscene.h.
Mesh* Cutscene::meshList[NUM_GEOMETRY] private
Definition at line 110 of file Cutscene.h.
Referenced by Init(), Map_Rendering(), Render(), and RenderSkybox().
MS Cutscene::modelStack private
Definition at line 112 of file Cutscene.h.
Referenced by Map_Rendering(), Render(), RenderMesh(), RenderSkybox(), RenderText(), and RenderTextOnScreen().
float Cutscene::planePos =-20 private
Definition at line 126 of file Cutscene.h.
Referenced by Render(), and Update().
float Cutscene::planePos2 = 350 private
Definition at line 127 of file Cutscene.h.
Referenced by Init(), Render(), and Update().
MS Cutscene::projectionStack private
Definition at line 112 of file Cutscene.h.
Referenced by Init(), RenderMesh(), RenderText(), and RenderTextOnScreen().
int Cutscene::randNum private
Definition at line 129 of file Cutscene.h.
Referenced by Character_Movement(), and Update().
float Cutscene::Size = 15
Definition at line 88 of file Cutscene.h.
Referenced by Map_Rendering().
Sound Cutscene::sound private
Definition at line 125 of file Cutscene.h.
Referenced by Init(), and Update().
float Cutscene::thrusterScale private
Definition at line 132 of file Cutscene.h.
Referenced by Render(), and Update().
MS Cutscene::viewStack private
Definition at line 112 of file Cutscene.h.
Referenced by Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
float Cutscene::X_Displacement = -100
Definition at line 90 of file Cutscene.h.
Referenced by Map_Rendering().
float Cutscene::Z_Displacement = 0
Definition at line 89 of file Cutscene.h.
Referenced by Map_Rendering().
The documentation for this class was generated from the following files:
MyGraphics/Source/Cutscene.h
MyGraphics/Source/Cutscene.cpp