My Application: Enemy Class Reference
Enemy Class Reference
#include <Enemy.h>
Public Member Functions
Enemy ()
~Enemy ()
bool Quick_check ()
int Return_HP ()
void Enemy_movement (Position Camera, float dt, float Size, char Map[20][20], Enemy enemy[5], int I, float Z_Displacement, float X_Displacement)
void DamageReceived (int Damage)
Position Return_Position ()
bool Collision_Detection (Position Character, float Size, char Map[20][20], Enemy enemy[5], int I, float Z_Displacement, float X_Displacement, bool enter=false)
Camera3 enemy_attack (Enemy enemy[5], Position character, Camera3 view)
Private Types
enum ModeType {
patrol, assassination, explore, fake_attack,
hold_down, speed_escape, Surprise_attack, strategic_planning,
charge
}
Private Member Functions
void mode_Action (Position Camera)
void mode_Change ()
Position Movement (Position Current, Position Target, float Speed, float Size, char Map[20][20], int I, Enemy enemy[5], float Z_Displacement, float X_Displacement)
bool Enemy_Collision (Position Character, Enemy enemy[5], int I)
Private Attributes
float HP
float MeleeDamage
signed int Current_modetype
Position position
Position Ground
Position SpawnPoint
Detailed Description
Definition at line 7 of file Enemy.h.
Member Enumeration Documentation
enum Enemy::ModeType private
Enumerator
patrol
assassination
explore
fake_attack
hold_down
speed_escape
Surprise_attack
strategic_planning
charge
Definition at line 16 of file Enemy.h.
Constructor & Destructor Documentation
Enemy::Enemy ()
Definition at line 5 of file Enemy.cpp.
References Current_modetype, Ground, HP, MeleeDamage, position, Quick_check(), and SpawnPoint.
Enemy::~Enemy ()
Definition at line 22 of file Enemy.cpp.
Member Function Documentation
bool Enemy::Collision_Detection (Position Character, float Size, char Map[20][20], Enemy enemy[5], int I, float Z_Displacement, float X_Displacement, bool enter = false)
Definition at line 297 of file Enemy.cpp.
References Enemy_Collision(), Position::x, and Position::z.
Referenced by Movement().
void Enemy::DamageReceived (int Damage)
Definition at line 95 of file Enemy.cpp.
References Ground, HP, mode_Change(), position, Quick_check(), and SpawnPoint.
Referenced by Bullet::CollideWithEnemy(), and CollisionDetector::swordCollision().
Camera3 Enemy::enemy_attack (Enemy enemy[5], Position character, Camera3 view)
Definition at line 387 of file Enemy.cpp.
References position, Camera3::Reset(), Position::x, and Position::z.
Referenced by Scene2::Enemy_Updating(), SP2::Enemy_Updating(), and Scene3::Enemy_Updating().
bool Enemy::Enemy_Collision (Position Character, Enemy enemy[5], int I) private
Definition at line 361 of file Enemy.cpp.
References position, Position::x, and Position::z.
Referenced by Collision_Detection().
void Enemy::Enemy_movement (Position Camera, float dt, float Size, char Map[20][20], Enemy enemy[5], int I, float Z_Displacement, float X_Displacement)
Definition at line 241 of file Enemy.cpp.
References charge, Current_modetype, fake_attack, Ground, mode_Action(), Movement(), position, speed_escape, and Surprise_attack.
Referenced by Scene2::Enemy_Updating(), SP2::Enemy_Updating(), and Scene3::Enemy_Updating().
void Enemy::mode_Action (Position Camera) private
Definition at line 114 of file Enemy.cpp.
References assassination, charge, Current_modetype, Math::DegreeToRadian(), explore, fake_attack, Ground, hold_down, patrol, SpawnPoint, speed_escape, strategic_planning, Surprise_attack, Position::x, and Position::z.
Referenced by Enemy_movement().
void Enemy::mode_Change () private
Definition at line 79 of file Enemy.cpp.
References Current_modetype, and HP.
Referenced by DamageReceived().
Position Enemy::Movement (Position Current, Position Target, float Speed, float Size, char Map[20][20], int I, Enemy enemy[5], float Z_Displacement, float X_Displacement) private
Definition at line 257 of file Enemy.cpp.
References Collision_Detection(), Position::x, and Position::z.
Referenced by Enemy_movement().
bool Enemy::Quick_check ()
Definition at line 26 of file Enemy.cpp.
References position, Position::x, and Position::z.
Referenced by DamageReceived(), and Enemy().
int Enemy::Return_HP ()
Definition at line 236 of file Enemy.cpp.
References HP.
Position Enemy::Return_Position ()
Definition at line 230 of file Enemy.cpp.
References position.
Referenced by Bullet::CollideWithEnemy(), Scene2::Enemy_Rendering(), SP2::Enemy_Rendering(), Scene3::Enemy_Rendering(), and CollisionDetector::swordCollision().
Field Documentation
signed int Enemy::Current_modetype private
Definition at line 11 of file Enemy.h.
Referenced by Enemy(), Enemy_movement(), mode_Action(), and mode_Change().
Position Enemy::Ground private
Definition at line 13 of file Enemy.h.
Referenced by DamageReceived(), Enemy(), Enemy_movement(), and mode_Action().
float Enemy::HP private
Definition at line 9 of file Enemy.h.
Referenced by DamageReceived(), Enemy(), mode_Change(), and Return_HP().
float Enemy::MeleeDamage private
Definition at line 10 of file Enemy.h.
Referenced by Enemy().
Position Enemy::position private
Definition at line 12 of file Enemy.h.
Referenced by DamageReceived(), Enemy(), enemy_attack(), Enemy_Collision(), Enemy_movement(), Quick_check(), and Return_Position().
Position Enemy::SpawnPoint private
Definition at line 14 of file Enemy.h.
Referenced by DamageReceived(), Enemy(), and mode_Action().
The documentation for this class was generated from the following files:
MyGraphics/Source/Enemy.h
MyGraphics/Source/Enemy.cpp