My Application: Scene3 Class Reference
Scene3 Class Reference
Class objects, meshes to render, booleans, floats and strings.
#include <Scene3.h>
Public Member Functions
Scene3 ()
Default constructor.
~Scene3 ()
Default destructor.
virtual void Init ()
Initializes for 3rd scene.
virtual void Update (double dt)
Updates the scene every frame (Animation/booleans/music etc)
virtual void Render ()
Main rendering function.
virtual void Exit ()
Exit and delete scene.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
char Map [20][20]
float Size = 15
float Z_Displacement = 0
float X_Displacement = -100
Private Types
enum GEOMETRY_TYPE {
GEO_TRIANGLE_1 = 0, GEO_TRIANGLE_2, GEO_REF_AXES, GEO_REF_QUAD,
GEO_LIGHTBALL, GEO_QUAD, GEO_PYRAMIDFLOOR, GEO_BB8HEAD,
GEO_BB8BODY, GEO_CROSSHAIR, GEO_LEFT1, GEO_RIGHT1,
GEO_TOP1, GEO_BOTTOM1, GEO_FRONT1, GEO_BACK1,
GEO_STAR, GEO_STORY1, GEO_TEXT, GEO_PATH,
GEO_AMMOICON, GEO_GOLDICON, GEO_EGGICON, GEO_BOMBICON,
GEO_OREICON, GEO_GUNICON, GEO_PICKAXEICON, GEO_SWORDICON,
GEO_VENDING, GEO_BOMB, GEO_CCTV, GEO_EGG,
GEO_BAG, GEO_PYRAMIDDOOR, GEO_INVENTORY, GEO_BUILDING,
GEO_COKE, GEO_BULLET, GEO_ROBOTH, GEO_ROBOTB,
GEO_ROBOT, GEO_ROBOT1, GEO_ROBOT2, GEO_SPEECH,
GEO_MOONBALL, GEO_PYRAMID, GEO_PYRAMIDNEW, GEO_PYRAMIDWALL,
GEO_PYRAMIDPILLAR, GEO_SPACESHIP, GEO_PLANEBODY, GEO_PLANEWING,
GEO_PLANEROCKET, GEO_PICKAXE, GEO_GUN, GEO_SWORD,
GEO_RMSMALL, GEO_RMMEDIUM, GEO_RMBIG, GEO_EXPLOSION,
GEO_BULLETSKIN, GEO_POTATO, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1ENABLED, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION,
U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION,
U_LIGHT2_COLOR, U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL,
U_LIGHT2_KQ, U_LIGHT2ENABLED, U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION,
U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT3_POSITION,
U_LIGHT3_COLOR, U_LIGHT3_POWER, U_LIGHT3_KC, U_LIGHT3_KL,
U_LIGHT3_KQ, U_LIGHT3ENABLED, U_LIGHT3_TYPE, U_LIGHT3_SPOTDIRECTION,
U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT, U_NUMLIGHTS,
U_COLOR_TEXTURE_ENABLED, U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR,
U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Mesh rendering function.
void UpdateMenu ()
void RenderSkybox ()
Renders skybox with rotation and scaling done.
void RenderText (Mesh *mesh, std::string text, Color color)
Text rendering function.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Text on screen rendering function.
void RenderQuadOnScreen (Mesh *mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z)
Renders meshlist/obj on screen.
void Dialogue (string filename)
Text pushed in array.
float checkNear (Camera3 camera, Vector3 rhs)
Camera position and item distance.
void Enemy_Rendering ()
Rendering Enemy In this scene.
void Enemy_Updating (float dt)
Updating Enemy In this scene.
void ObjectsHolding (Mesh *mesh, float size)
hold objects or parts
void Map_Reading ()
Reading map form Txt file for this scene.
void Map_Rendering ()
Rendering map based on Txt file for this scene.
void Character_Movement (float dt)
Platers controls for this scene.
void Plane_Rendering ()
Private Attributes
unsigned m_vertexArrayID
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
NPC npc
bool robot1moved = false
bool robot1rotate = false
float robot1rotation = 0
float xtranslate
float ytranslate
int parts = 0
Mesh * meshList [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
float LSPEED = 10.f
float moveSkyBoxZ = 91.f
float moveSkyBoxX = 0.f
float potatoRotate
Light light [8]
string new_line
Camera3 camera
Sound sound
vector< string > my_arr
vector< Bullet * > bullet_arr
Vector3 RobotPosition1
double b_coolDown
double b_coolDownLimit
bool startCoolDdown
int b_Ammo
float storyPosition
bool storyDismiss
bool storyShow
string story
float deltaTime
Bullet bullet
int Died_Time = 0
Enemy enemy [5]
float throwingdown = 0
float throwingforward = 0
float throwup = 0
Vector3 newcameraposition = (0, 0, 0)
Vector3 oldcameraposition = (0, 0, 0)
bool throwbomb = false
bool thrown = false
bool toggle = false
bool cam1 = false
bool movement = true
bool plantbomb = false
float followx = 0
float followy = 0
float coolDownTime
string shop
bool doorinteract = true
float JumpTime
float PressTime
Mouse mouse
CollisionDetector detectCollision
bool On_Plane = false
float Speed = 0
Position Plane
Animation animation
float swordRotation
float pickAxeRotation
float gunRotation
float gunTranslation
float swordTranslation
float pickAxeTranslation
bool playSlashingAnimation
bool playShootingAnimation
bool playMiningAnimation
bool usingSword
bool usingGun
bool usingPickAxe
int weaponChoice
int gun
int sword
int pickaxe
rawMaterial oreMaterial_arr [3]
double rm_coolDown
double rm_coolDownLimit
bool startRMcoolDown
Detailed Description
Class objects, meshes to render, booleans, floats and strings.
Class SceneWin:
Definition at line 48 of file Scene3.h.
Member Enumeration Documentation
enum Scene3::GEOMETRY_TYPE private
Enumerator
GEO_TRIANGLE_1
GEO_TRIANGLE_2
GEO_REF_AXES
GEO_REF_QUAD
GEO_LIGHTBALL
GEO_QUAD
GEO_PYRAMIDFLOOR
GEO_BB8HEAD
GEO_BB8BODY
GEO_CROSSHAIR
GEO_LEFT1
GEO_RIGHT1
GEO_TOP1
GEO_BOTTOM1
GEO_FRONT1
GEO_BACK1
GEO_STAR
GEO_STORY1
GEO_TEXT
GEO_PATH
GEO_AMMOICON
GEO_GOLDICON
GEO_EGGICON
GEO_BOMBICON
GEO_OREICON
GEO_GUNICON
GEO_PICKAXEICON
GEO_SWORDICON
GEO_VENDING
GEO_BOMB
GEO_CCTV
GEO_EGG
GEO_BAG
GEO_PYRAMIDDOOR
GEO_INVENTORY
GEO_BUILDING
GEO_COKE
GEO_BULLET
GEO_ROBOTH
GEO_ROBOTB
GEO_ROBOT
GEO_ROBOT1
GEO_ROBOT2
GEO_SPEECH
GEO_MOONBALL
GEO_PYRAMID
GEO_PYRAMIDNEW
GEO_PYRAMIDWALL
GEO_PYRAMIDPILLAR
GEO_SPACESHIP
GEO_PLANEBODY
GEO_PLANEWING
GEO_PLANEROCKET
GEO_PICKAXE
GEO_GUN
GEO_SWORD
GEO_RMSMALL
GEO_RMMEDIUM
GEO_RMBIG
GEO_EXPLOSION
GEO_BULLETSKIN
GEO_POTATO
NUM_GEOMETRY
Definition at line 50 of file Scene3.h.
enum Scene3::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1ENABLED
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2ENABLED
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_LIGHT3_POSITION
U_LIGHT3_COLOR
U_LIGHT3_POWER
U_LIGHT3_KC
U_LIGHT3_KL
U_LIGHT3_KQ
U_LIGHT3ENABLED
U_LIGHT3_TYPE
U_LIGHT3_SPOTDIRECTION
U_LIGHT3_COSCUTOFF
U_LIGHT3_COSINNER
U_LIGHT3_EXPONENT
U_NUMLIGHTS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 118 of file Scene3.h.
Constructor & Destructor Documentation
Scene3::Scene3 ()
Default constructor.
Exceptions
None
Returns
None
Definition at line 55 of file Scene3.cpp.
Scene3::~Scene3 ()
Default destructor.
Exceptions
None
Returns
None
Definition at line 67 of file Scene3.cpp.
Member Function Documentation
void Scene3::Character_Movement (float dt) private
Platers controls for this scene.
Exceptions
None
Returns
None
Definition at line 1754 of file Scene3.cpp.
References camera, Camera3::cameraRotate, Camera3::cameraSpeed, checkNear(), NPC::DOT::Collision, Vector3::Cross(), Camera3::defaultUp, Math::DegreeToRadian(), NPC::door, doorinteract, enemy, followx, followy, SharedData::gameState, SharedData::GetInstance(), Application::IsKeyPressed(), light, m_parameters, Map, Camera3::maxCameraX, Camera3::maxX, Camera3::maxZ, Camera3::minX, Camera3::minZ, npc, NPC::DOT::Nposition, On_Plane, Plane, plantbomb, Camera::position, Light::position, Light::power, Camera3::Reset(), SharedData::SCENE3, Vector3::Set(), Size, Speed, SharedData::stateCheck, Camera::target, U_LIGHT3_POWER, Camera::up, Camera3::view, VtoP(), Position::x, Vector3::x, X_Displacement, Position::y, Vector3::y, Position::z, Vector3::z, and Z_Displacement.
Referenced by Update().
float Scene3::checkNear (Camera3 camera, Vector3 rhs) private
Camera position and item distance.
Parameters
camera Passes in camera
rhs Object position
Exceptions
None
Returns
the distance between objects
Definition at line 469 of file Scene3.cpp.
References Camera::position, Vector3::x, and Vector3::z.
Referenced by Character_Movement(), and Update().
void Scene3::Dialogue (string filename) private
Text pushed in array.
Parameters
filename Passes in the text file to be pushed into array
Exceptions
None
Returns
None
Definition at line 910 of file Scene3.cpp.
References my_arr, and new_line.
Referenced by Init().
void Scene3::Enemy_Rendering () private
Rendering Enemy In this scene.
Exceptions
None
Returns
None
Definition at line 1653 of file Scene3.cpp.
References enemy, GEO_COKE, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), Enemy::Return_Position(), MS::Scale(), MS::Translate(), Position::x, and Position::z.
Referenced by Render().
void Scene3::Enemy_Updating (float dt) private
Updating Enemy In this scene.
Exceptions
None
Returns
None
Definition at line 1635 of file Scene3.cpp.
References camera, enemy, Enemy::Enemy_movement(), Map, Camera::position, Size, Vector3::x, X_Displacement, Vector3::y, Vector3::z, and Z_Displacement.
Referenced by Update().
void Scene3::Exit () virtual
Exit and delete scene.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 1620 of file Scene3.cpp.
References m_programID, and m_vertexArrayID.
void Scene3::Init () virtual
Initializes for 3rd scene.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 79 of file Scene3.cpp.
References b_coolDown, b_coolDownLimit, NPC::bomb, camera, Camera3::cameraRotate, NPC::DOT::canGoThrough, NPC::DOT::Collision, Light::color, Light::cosCutOff, Light::cosInner, Math::DegreeToRadian(), Dialogue(), NPC::door, Light::exponent, SharedData::gameScene, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateOBJ(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRepeatQuad(), MeshBuilder::GenerateText(), GEO_AMMOICON, GEO_BACK1, GEO_BOMB, GEO_BOMBICON, GEO_BOTTOM1, GEO_BULLETSKIN, GEO_CCTV, GEO_COKE, GEO_CROSSHAIR, GEO_EGGICON, GEO_EXPLOSION, GEO_FRONT1, GEO_GOLDICON, GEO_GUN, GEO_GUNICON, GEO_LEFT1, GEO_MOONBALL, GEO_OREICON, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, GEO_POTATO, GEO_PYRAMID, GEO_PYRAMIDDOOR, GEO_PYRAMIDFLOOR, GEO_PYRAMIDNEW, GEO_PYRAMIDPILLAR, GEO_PYRAMIDWALL, GEO_QUAD, GEO_REF_AXES, GEO_RIGHT1, GEO_RMBIG, GEO_RMMEDIUM, GEO_RMSMALL, GEO_ROBOT, GEO_ROBOT1, GEO_ROBOTB, GEO_ROBOTH, GEO_SPACESHIP, GEO_SPEECH, GEO_STORY1, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, GEO_TOP1, SharedData::GetInstance(), gun, gunRotation, gunTranslation, Camera3::Init(), JumpTime, Material::kAmbient, Light::kC, Material::kDiffuse, Light::kL, Light::kQ, Material::kShininess, Material::kSpecular, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, Light::LIGHT_SPOT, MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, Map_Reading(), Mesh::material, meshList, npc, NPC::DOT::Nposition, On_Plane, oreMaterial_arr, pickAxeRotation, pickAxeTranslation, Plane, Sound::playMusic(), rawMaterial::pos, Light::position, potatoRotate, Light::power, PressTime, projectionStack, rm_coolDown, rm_coolDownLimit, NPC::robot1, NPC::robot2, NPC::robot3, Position::Set(), Component::Set(), Color::Set(), Vector3::Set(), Mtx44::SetToPerspective(), sound, NPC::spacebody, NPC::spaceShip, Light::spotDirection, startCoolDdown, startRMcoolDown, storyPosition, storyShow, swordRotation, swordTranslation, Mesh::textureID, Light::type, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHT2_COLOR, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER, U_LIGHT2_EXPONENT, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ, U_LIGHT2_POSITION, U_LIGHT2_POWER, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_TYPE, U_LIGHT3_COLOR, U_LIGHT3_COSCUTOFF, U_LIGHT3_COSINNER, U_LIGHT3_EXPONENT, U_LIGHT3_KC, U_LIGHT3_KL, U_LIGHT3_KQ, U_LIGHT3_POSITION, U_LIGHT3_POWER, U_LIGHT3_SPOTDIRECTION, U_LIGHT3_TYPE, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_NUMLIGHTS, U_TEXT_COLOR, U_TEXT_ENABLED, usingGun, usingPickAxe, usingSword, and weaponChoice.
void Scene3::Map_Reading () private
Reading map form Txt file for this scene.
Exceptions
None
Returns
None
Definition at line 1675 of file Scene3.cpp.
References Map.
Referenced by Init().
void Scene3::Map_Rendering () private
Rendering map based on Txt file for this scene.
Exceptions
None
Returns
None
Definition at line 1703 of file Scene3.cpp.
References GEO_POTATO, GEO_PYRAMIDNEW, GEO_PYRAMIDPILLAR, GEO_PYRAMIDWALL, Map, meshList, modelStack, MS::PopMatrix(), potatoRotate, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Size, MS::Translate(), X_Displacement, and Z_Displacement.
Referenced by Render().
void Scene3::ObjectsHolding (Mesh * mesh, float size) private
hold objects or parts
Parameters
mesh Takes in which mesh to render out
size Scale of the mesh to render out
Exceptions
None
Returns
None
Definition at line 2017 of file Scene3.cpp.
References camera, followx, followy, modelStack, MS::PopMatrix(), Camera::position, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
void Scene3::Plane_Rendering () private
Definition at line 2034 of file Scene3.cpp.
References GEO_PLANEBODY, GEO_PLANEROCKET, GEO_PLANEWING, meshList, modelStack, Plane, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Position::x, Position::y, and Position::z.
Referenced by Render().
void Scene3::Render () virtual
Main rendering function.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 1184 of file Scene3.cpp.
References SharedData::bomb, NPC::bomb, SharedData::bullet, bullet_arr, camera, NPC::DOT::canInteract, CollisionDetector::collideByDist(), deltaTime, detectCollision, NPC::dialogue, NPC::dialoguePlus, Died_Time, NPC::door, doorinteract, SharedData::egg, enemy, Enemy_Rendering(), followx, followy, GEO_AMMOICON, GEO_BOMB, GEO_BOMBICON, GEO_BULLETSKIN, GEO_CCTV, GEO_CROSSHAIR, GEO_EGGICON, GEO_GOLDICON, GEO_GUN, GEO_GUNICON, GEO_MOONBALL, GEO_OREICON, GEO_PICKAXE, GEO_PICKAXEICON, GEO_PYRAMIDDOOR, GEO_PYRAMIDFLOOR, GEO_QUAD, GEO_ROBOT, GEO_ROBOT1, GEO_ROBOTB, GEO_ROBOTH, GEO_SPACESHIP, GEO_SPEECH, GEO_STORY1, GEO_SWORD, GEO_SWORDICON, GEO_TEXT, SharedData::GetInstance(), SharedData::gold, gun, gunRotation, gunTranslation, NPC::interactDia, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, Map_Rendering(), meshList, SharedData::mineral, modelStack, my_arr, npc, NPC::DOT::Nposition, On_Plane, oreMaterial_arr, pickaxe, pickAxeRotation, pickAxeTranslation, Plane, Plane_Rendering(), plantbomb, MS::PopMatrix(), rawMaterial::pos, Camera::position, Light::position, potatoRotate, MS::PushMatrix(), SharedData::INVENTORY::quantity, RenderMesh(), RenderQuadOnScreen(), RenderSkybox(), RenderTextOnScreen(), Camera3::Reset(), NPC::DOT::robot, NPC::robot1, robot1rotation, NPC::robot2, NPC::robot3, MS::Rotate(), MS::Scale(), shop, NPC::spaceShip, NPC::speech, Light::spotDirection, storyDismiss, storyPosition, sword, swordRotation, swordTranslation, Camera::target, throwup, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, U_LIGHT2_POSITION, U_LIGHT2_SPOTDIRECTION, U_LIGHT3_POSITION, U_LIGHT3_SPOTDIRECTION, Camera::up, viewStack, VtoP(), Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void Scene3::RenderMesh (Mesh * mesh, bool enableLight) private
Mesh rendering function.
Exceptions
None
Returns
None
Definition at line 930 of file Scene3.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, Lighting9, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Enemy_Rendering(), Map_Rendering(), ObjectsHolding(), Plane_Rendering(), Render(), RenderQuadOnScreen(), and RenderSkybox().
void Scene3::RenderQuadOnScreen (Mesh * mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z) private
Renders meshlist/obj on screen.
Parameters
mesh The mesh to render
size Scale of the mesh to render
x,y and z Position of the mesh to render
rotate,rx,ry and rz Rotation of mesh to render
z Z layering
Exceptions
None
Returns
None
Definition at line 1088 of file Scene3.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void Scene3::RenderSkybox () private
Renders skybox with rotation and scaling done.
Exceptions
None
Returns
None
Definition at line 1116 of file Scene3.cpp.
References GEO_BACK1, GEO_BOTTOM1, GEO_FRONT1, GEO_LEFT1, GEO_RIGHT1, GEO_TOP1, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), SBSCALE1, MS::Scale(), and MS::Translate().
Referenced by Render().
void Scene3::RenderText (Mesh * mesh, std::string text, Color color) private
Text rendering function.
Exceptions
None
Returns
None
Definition at line 979 of file Scene3.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void Scene3::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Text on screen rendering function.
Exceptions
None
Returns
None
Definition at line 1014 of file Scene3.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, viewStack, xtranslate, and ytranslate.
Referenced by Render().
void Scene3::Update (double dt) virtual
Updates the scene every frame (Animation/booleans/music etc)
Exceptions
None
Returns
None
when untoggle below runs agains
Implements Scene.
Definition at line 483 of file Scene3.cpp.
References animation, b_coolDown, b_coolDownLimit, SharedData::bomb, NPC::bomb, SharedData::bullet, bullet, bullet_arr, cam1, camera, NPC::DOT::canGoThrough, NPC::DOT::canInteract, Character_Movement(), checkNear(), CollisionDetector::collideByDist(), NPC::DOT::Collision, coolDownTime, SharedData::CUTSCENE, deltaTime, detectCollision, NPC::dialoguePlus, NPC::door, NPC::Door(), enemy, Enemy_Updating(), followx, followy, SharedData::gameState, GEO_RMBIG, GEO_RMMEDIUM, GEO_RMSMALL, SharedData::GetInstance(), gun, gunTranslation, rawMaterial::hp, NPC::interactDia, rawMaterial::isAlive, Application::IsKeyPressed(), Lighting9, meshList, Animation::Mine(), SharedData::mineral, mouse, Mouse::MouseUpdate(), Animation::moveGun(), movement, Animation::moveSword(), my_arr, newcameraposition, npc, NPC::DOT::Nposition, oldcameraposition, On_Plane, oreMaterial_arr, pickaxe, pickAxeRotation, pickAxeTranslation, plantbomb, playMiningAnimation, Sound::playSE(), playShootingAnimation, playSlashingAnimation, rawMaterial::pos, Camera::position, potatoRotate, SharedData::INVENTORY::quantity, rm_coolDown, rm_coolDownLimit, NPC::DOT::robot, NPC::robot1, robot1moved, robot1rotate, robot1rotation, NPC::robot3, NPC::Scene1(), rawMaterial::shape, Animation::Shoot(), SharedData::SHOP, Animation::Slash(), sound, NPC::spacebody, NPC::spaceShip, startCoolDdown, startRMcoolDown, SharedData::stateCheck, Sound::stopMusic(), storyDismiss, storyPosition, storyShow, sword, CollisionDetector::swordCollision(), swordRotation, swordTranslation, Mesh::textureID, toggle, usingGun, usingPickAxe, usingSword, weaponChoice, Vector3::y, and Vector3::z.
void Scene3::UpdateMenu () private
Field Documentation
Animation Scene3::animation private
Definition at line 304 of file Scene3.h.
Referenced by Update().
int Scene3::b_Ammo private
Definition at line 250 of file Scene3.h.
double Scene3::b_coolDown private
Definition at line 247 of file Scene3.h.
Referenced by Init(), and Update().
double Scene3::b_coolDownLimit private
Definition at line 248 of file Scene3.h.
Referenced by Init(), and Update().
Bullet Scene3::bullet private
Definition at line 259 of file Scene3.h.
Referenced by Update().
vector<Bullet*> Scene3::bullet_arr private
Definition at line 245 of file Scene3.h.
Referenced by Render(), and Update().
bool Scene3::cam1 = false private
Definition at line 276 of file Scene3.h.
Referenced by Update().
Camera3 Scene3::camera private
Definition at line 241 of file Scene3.h.
Referenced by Character_Movement(), Enemy_Updating(), Init(), ObjectsHolding(), Render(), and Update().
float Scene3::coolDownTime private
Definition at line 283 of file Scene3.h.
Referenced by Update().
float Scene3::deltaTime private
Definition at line 258 of file Scene3.h.
Referenced by Render(), and Update().
CollisionDetector Scene3::detectCollision private
Definition at line 297 of file Scene3.h.
Referenced by Render(), and Update().
int Scene3::Died_Time = 0 private
Definition at line 261 of file Scene3.h.
Referenced by Render().
bool Scene3::doorinteract = true private
Definition at line 285 of file Scene3.h.
Referenced by Character_Movement(), and Render().
Enemy Scene3::enemy[5] private
Definition at line 262 of file Scene3.h.
Referenced by Character_Movement(), Enemy_Rendering(), Enemy_Updating(), Render(), and Update().
float Scene3::followx = 0 private
Definition at line 281 of file Scene3.h.
Referenced by Character_Movement(), ObjectsHolding(), Render(), and Update().
float Scene3::followy = 0 private
Definition at line 282 of file Scene3.h.
Referenced by Character_Movement(), ObjectsHolding(), Render(), and Update().
int Scene3::gun private
Definition at line 322 of file Scene3.h.
Referenced by Init(), Render(), and Update().
float Scene3::gunRotation private
Definition at line 307 of file Scene3.h.
Referenced by Init(), and Render().
float Scene3::gunTranslation private
Definition at line 309 of file Scene3.h.
Referenced by Init(), Render(), and Update().
float Scene3::JumpTime private
Definition at line 293 of file Scene3.h.
Referenced by Init().
Light Scene3::light[8] private
Definition at line 229 of file Scene3.h.
Referenced by Character_Movement(), Init(), and Render().
float Scene3::LSPEED = 10.f private
Definition at line 224 of file Scene3.h.
unsigned Scene3::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 208 of file Scene3.h.
unsigned Scene3::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 206 of file Scene3.h.
unsigned Scene3::m_parameters[U_TOTAL] private
Definition at line 210 of file Scene3.h.
Referenced by Character_Movement(), Init(), Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned Scene3::m_programID private
Definition at line 209 of file Scene3.h.
Referenced by Exit(), and Init().
unsigned Scene3::m_vertexArrayID private
Definition at line 205 of file Scene3.h.
Referenced by Exit(), and Init().
unsigned Scene3::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 207 of file Scene3.h.
char Scene3::Map[20][20]
Definition at line 190 of file Scene3.h.
Referenced by Character_Movement(), Enemy_Updating(), Map_Reading(), and Map_Rendering().
Mesh* Scene3::meshList[NUM_GEOMETRY] private
Definition at line 221 of file Scene3.h.
Referenced by Enemy_Rendering(), Init(), Map_Rendering(), Plane_Rendering(), Render(), RenderSkybox(), and Update().
MS Scene3::modelStack private
Definition at line 223 of file Scene3.h.
Referenced by Enemy_Rendering(), Map_Rendering(), ObjectsHolding(), Plane_Rendering(), Render(), RenderMesh(), RenderQuadOnScreen(), RenderSkybox(), RenderText(), and RenderTextOnScreen().
Mouse Scene3::mouse private
Definition at line 296 of file Scene3.h.
Referenced by Update().
bool Scene3::movement = true private
Definition at line 277 of file Scene3.h.
Referenced by Update().
float Scene3::moveSkyBoxX = 0.f private
Definition at line 226 of file Scene3.h.
float Scene3::moveSkyBoxZ = 91.f private
Definition at line 225 of file Scene3.h.
vector<string> Scene3::my_arr private
Definition at line 244 of file Scene3.h.
Referenced by Dialogue(), Render(), and Update().
string Scene3::new_line private
Definition at line 236 of file Scene3.h.
Referenced by Dialogue().
Vector3 Scene3::newcameraposition = (0, 0, 0) private
Definition at line 271 of file Scene3.h.
Referenced by Update().
NPC Scene3::npc private
Definition at line 213 of file Scene3.h.
Referenced by Character_Movement(), Init(), Render(), and Update().
Vector3 Scene3::oldcameraposition = (0, 0, 0) private
Definition at line 272 of file Scene3.h.
Referenced by Update().
bool Scene3::On_Plane = false private
Definition at line 299 of file Scene3.h.
Referenced by Character_Movement(), Init(), Render(), and Update().
rawMaterial Scene3::oreMaterial_arr[3] private
Definition at line 326 of file Scene3.h.
Referenced by Init(), Render(), and Update().
int Scene3::parts = 0 private
Definition at line 218 of file Scene3.h.
int Scene3::pickaxe private
Definition at line 324 of file Scene3.h.
Referenced by Render(), and Update().
float Scene3::pickAxeRotation private
Definition at line 306 of file Scene3.h.
Referenced by Init(), Render(), and Update().
float Scene3::pickAxeTranslation private
Definition at line 311 of file Scene3.h.
Referenced by Init(), Render(), and Update().
Position Scene3::Plane private
Definition at line 301 of file Scene3.h.
Referenced by Character_Movement(), Init(), Plane_Rendering(), and Render().
bool Scene3::plantbomb = false private
Definition at line 278 of file Scene3.h.
Referenced by Character_Movement(), Render(), and Update().
bool Scene3::playMiningAnimation private
Definition at line 315 of file Scene3.h.
Referenced by Update().
bool Scene3::playShootingAnimation private
Definition at line 314 of file Scene3.h.
Referenced by Update().
bool Scene3::playSlashingAnimation private
Definition at line 313 of file Scene3.h.
Referenced by Update().
float Scene3::potatoRotate private
Definition at line 227 of file Scene3.h.
Referenced by Init(), Map_Rendering(), Render(), and Update().
float Scene3::PressTime private
Definition at line 294 of file Scene3.h.
Referenced by Init().
MS Scene3::projectionStack private
Definition at line 223 of file Scene3.h.
Referenced by Init(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
double Scene3::rm_coolDown private
Definition at line 327 of file Scene3.h.
Referenced by Init(), and Update().
double Scene3::rm_coolDownLimit private
Definition at line 328 of file Scene3.h.
Referenced by Init(), and Update().
bool Scene3::robot1moved = false private
Definition at line 214 of file Scene3.h.
Referenced by Update().
bool Scene3::robot1rotate = false private
Definition at line 215 of file Scene3.h.
Referenced by Update().
float Scene3::robot1rotation = 0 private
Definition at line 216 of file Scene3.h.
Referenced by Render(), and Update().
Vector3 Scene3::RobotPosition1 private
Definition at line 246 of file Scene3.h.
string Scene3::shop private
Definition at line 284 of file Scene3.h.
Referenced by Render().
float Scene3::Size = 15
Definition at line 191 of file Scene3.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
Sound Scene3::sound private
Definition at line 242 of file Scene3.h.
Referenced by Init(), and Update().
float Scene3::Speed = 0 private
Definition at line 300 of file Scene3.h.
Referenced by Character_Movement().
bool Scene3::startCoolDdown private
Definition at line 249 of file Scene3.h.
Referenced by Init(), and Update().
bool Scene3::startRMcoolDown private
Definition at line 329 of file Scene3.h.
Referenced by Init(), and Update().
string Scene3::story private
Definition at line 256 of file Scene3.h.
bool Scene3::storyDismiss private
Definition at line 254 of file Scene3.h.
Referenced by Render(), and Update().
float Scene3::storyPosition private
Definition at line 253 of file Scene3.h.
Referenced by Init(), Render(), and Update().
bool Scene3::storyShow private
Definition at line 255 of file Scene3.h.
Referenced by Init(), and Update().
int Scene3::sword private
Definition at line 323 of file Scene3.h.
Referenced by Render(), and Update().
float Scene3::swordRotation private
Definition at line 305 of file Scene3.h.
Referenced by Init(), Render(), and Update().
float Scene3::swordTranslation private
Definition at line 310 of file Scene3.h.
Referenced by Init(), Render(), and Update().
bool Scene3::throwbomb = false private
Definition at line 273 of file Scene3.h.
float Scene3::throwingdown = 0 private
Definition at line 268 of file Scene3.h.
float Scene3::throwingforward = 0 private
Definition at line 269 of file Scene3.h.
bool Scene3::thrown = false private
Definition at line 274 of file Scene3.h.
float Scene3::throwup = 0 private
Definition at line 270 of file Scene3.h.
Referenced by Render().
bool Scene3::toggle = false private
Definition at line 275 of file Scene3.h.
Referenced by Update().
bool Scene3::usingGun private
Definition at line 318 of file Scene3.h.
Referenced by Init(), and Update().
bool Scene3::usingPickAxe private
Definition at line 319 of file Scene3.h.
Referenced by Init(), and Update().
bool Scene3::usingSword private
Definition at line 317 of file Scene3.h.
Referenced by Init(), and Update().
MS Scene3::viewStack private
Definition at line 223 of file Scene3.h.
Referenced by Render(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
int Scene3::weaponChoice private
Definition at line 320 of file Scene3.h.
Referenced by Init(), and Update().
float Scene3::X_Displacement = -100
Definition at line 193 of file Scene3.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
float Scene3::xtranslate private
Definition at line 217 of file Scene3.h.
Referenced by RenderTextOnScreen().
float Scene3::ytranslate private
Definition at line 217 of file Scene3.h.
Referenced by RenderTextOnScreen().
float Scene3::Z_Displacement = 0
Definition at line 192 of file Scene3.h.
Referenced by Character_Movement(), Enemy_Updating(), and Map_Rendering().
The documentation for this class was generated from the following files:
MyGraphics/Source/Scene3.h
MyGraphics/Source/Scene3.cpp