My Application: CollisionDetector Class Reference
CollisionDetector Class Reference
Defines a player's weapons collision in game and its methods.
#include <CollisionDetector.h>
Public Member Functions
CollisionDetector ()
CollisionDetector() is a constructor for Bullet class, where I set the default values needed for the methods.
~CollisionDetector ()
~CollisionDetector() is a destructor for the class
float collideByDist (Vector3 object, Vector3 target)
collideByDist(Vector3 object, Vector3 target) is a calculator function for CollisionDetector class, where I calculate the distance between 2 Vector3.
bool swordCollision (Enemy enemy[], Vector3 player)
swordCollision(Enemy enemy[], Vector3 player) is a checker function for player's melee attack, if it hit the enemy or not.
Vector3 PtoV (Position V)
PtoV(Position V) is a convertor function for CollisionDetector class, where I convert the position values into a vector.
Data Fields
float dist
float diffInX
float diffInZ
Detailed Description
Defines a player's weapons collision in game and its methods.
Class Dweller:
Definition at line 26 of file CollisionDetector.h.
Constructor & Destructor Documentation
CollisionDetector::CollisionDetector ()
CollisionDetector() is a constructor for Bullet class, where I set the default values needed for the methods.
Definition at line 25 of file CollisionDetector.cpp.
CollisionDetector::~CollisionDetector ()
~CollisionDetector() is a destructor for the class
Definition at line 36 of file CollisionDetector.cpp.
Member Function Documentation
float CollisionDetector::collideByDist (Vector3 object, Vector3 target)
collideByDist(Vector3 object, Vector3 target) is a calculator function for CollisionDetector class, where I calculate the distance between 2 Vector3.
Parameters
object A Vector3 values of an object that needs to be calculated with another to find their distance.
target A Vector3 values of a target that needs to be calculated with another to find their distance.
Returns
A float value that represent the distance between the 2 Vector3
Definition at line 82 of file CollisionDetector.cpp.
References diffInX, diffInZ, dist, Vector3::x, and Vector3::z.
Referenced by Bullet::CollideWithEnemy(), NPC::Door(), Scene3::Render(), SP2::Render(), Scene2::Render(), NPC::Scene1(), NPC::Shop(), swordCollision(), Shop::Update(), Scene3::Update(), SP2::Update(), and Scene2::Update().
Vector3 CollisionDetector::PtoV (Position V)
PtoV(Position V) is a convertor function for CollisionDetector class, where I convert the position values into a vector.
Parameters
V A Position values that need to be convert to Vector3.
Returns
A Vector3 that has been converted from a position
Definition at line 54 of file CollisionDetector.cpp.
References Position::x, Position::y, and Position::z.
Referenced by swordCollision().
bool CollisionDetector::swordCollision (Enemy enemy[], Vector3 player)
swordCollision(Enemy enemy[], Vector3 player) is a checker function for player's melee attack, if it hit the enemy or not.
Parameters
enemy[] An enemy array that stores the enemy
player A Vector3 values of the player position
Returns
A boolean that represent if the player hit the enemy
Definition at line 115 of file CollisionDetector.cpp.
References collideByDist(), Enemy::DamageReceived(), SharedData::enemycounter, SharedData::GetInstance(), PtoV(), and Enemy::Return_Position().
Referenced by Scene3::Update(), SP2::Update(), and Scene2::Update().
Field Documentation
float CollisionDetector::diffInX
Definition at line 31 of file CollisionDetector.h.
Referenced by collideByDist().
float CollisionDetector::diffInZ
Definition at line 32 of file CollisionDetector.h.
Referenced by collideByDist().
float CollisionDetector::dist
Definition at line 30 of file CollisionDetector.h.
Referenced by collideByDist().
The documentation for this class was generated from the following files:
MyGraphics/Source/CollisionDetector.h
MyGraphics/Source/CollisionDetector.cpp