My Application: SceneWin Class Reference
SceneWin Class Reference
Mesh list, floats and booleans to render the win scene.
#include <SceneWin.h>
Public Member Functions
SceneWin ()
Default constructor.
~SceneWin ()
Default destructor.
virtual void Init ()
Initializes for win scene, any booleans/strings/floats and meshes.
virtual void Update (double dt)
Updates the scene every frame (Animation/booleans/music etc)
virtual void Render ()
The main render function for this scene, renders any text/meshes.
virtual void Exit ()
Delete scene.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Private Types
enum GEOMETRY_TYPE {
GEO_REF_AXES = 0, GEO_QUAD, GEO_STAR, GEO_TEXT,
GEO_PATH, GEO_VENDING, GEO_COKE, GEO_INSTRUCTIONS,
GEO_PLANEWING, GEO_PLANEROCKET, GEO_PLANEBODY, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_TOTAL
}
Private Member Functions
void RenderMesh (Mesh *mesh, bool enableLight)
Mesh rendering function.
void RenderText (Mesh *mesh, std::string text, Color color)
Renders text in the game.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
Renders text on screen in the game.
void RenderQuadOnScreen (Mesh *mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z)
Renders any meshList items/obj on the screen.
void Dialogue (string filename)
Private Attributes
unsigned m_vertexArrayID
unsigned m_indexBuffer [NUM_GEOMETRY]
unsigned m_vertexBuffer [NUM_GEOMETRY]
unsigned m_colorBuffer [NUM_GEOMETRY]
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Mesh * meshList [NUM_GEOMETRY]
MS modelStack
MS viewStack
MS projectionStack
float LSPEED = 10.f
float moveSkyBoxZ = 91.f
float moveSkyBoxX = 0.f
Camera3 camera
Sound sound
Detailed Description
Mesh list, floats and booleans to render the win scene.
Class SceneWin:
Definition at line 30 of file SceneWin.h.
Member Enumeration Documentation
enum SceneWin::GEOMETRY_TYPE private
Enumerator
GEO_REF_AXES
GEO_QUAD
GEO_STAR
GEO_TEXT
GEO_PATH
GEO_VENDING
GEO_COKE
GEO_INSTRUCTIONS
GEO_PLANEWING
GEO_PLANEROCKET
GEO_PLANEBODY
NUM_GEOMETRY
Definition at line 32 of file SceneWin.h.
enum SceneWin::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_TOTAL
Definition at line 48 of file SceneWin.h.
Constructor & Destructor Documentation
SceneWin::SceneWin ()
Default constructor.
Exceptions
None
Returns
None
Definition at line 29 of file SceneWin.cpp.
SceneWin::~SceneWin ()
Default destructor.
Exceptions
None
Returns
None
Definition at line 41 of file SceneWin.cpp.
Member Function Documentation
void SceneWin::Dialogue (string filename) private
void SceneWin::Exit () virtual
Delete scene.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 315 of file SceneWin.cpp.
References m_programID, and m_vertexArrayID.
void SceneWin::Init () virtual
Initializes for win scene, any booleans/strings/floats and meshes.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 53 of file SceneWin.cpp.
References camera, MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), GEO_PATH, GEO_TEXT, Camera3::Init(), MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, Sound::playMusic(), projectionStack, Mtx44::SetToPerspective(), sound, Mesh::textureID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_TEXT_COLOR, and U_TEXT_ENABLED.
void SceneWin::Render () virtual
The main render function for this scene, renders any text/meshes.
Exceptions
None
Returns
None
Implements Scene.
Definition at line 283 of file SceneWin.cpp.
References camera, SharedData::enemycounter, GEO_PATH, GEO_TEXT, SharedData::GetInstance(), MS::LoadIdentity(), MS::LookAt(), meshList, modelStack, Camera::position, RenderQuadOnScreen(), RenderTextOnScreen(), Camera::target, Camera::up, viewStack, Vector3::x, Vector3::y, and Vector3::z.
void SceneWin::RenderMesh (Mesh * mesh, bool enableLight) private
Mesh rendering function.
Exceptions
None
Returns
None
Definition at line 133 of file SceneWin.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MODELVIEW, U_MVP, and viewStack.
Referenced by RenderQuadOnScreen().
void SceneWin::RenderQuadOnScreen (Mesh * mesh, float size, float x, float y, float rotate, float rx, float ry, float rz, float z) private
Renders any meshList items/obj on the screen.
Exceptions
None
Returns
None
Definition at line 256 of file SceneWin.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), and viewStack.
Referenced by Render().
void SceneWin::RenderText (Mesh * mesh, std::string text, Color color) private
Renders text in the game.
Exceptions
None
Returns
None
Definition at line 168 of file SceneWin.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void SceneWin::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Renders text on screen in the game.
Exceptions
None
Returns
None
Definition at line 203 of file SceneWin.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void SceneWin::Update (double dt) virtual
Updates the scene every frame (Animation/booleans/music etc)
Exceptions
None
Returns
None
Implements Scene.
Definition at line 115 of file SceneWin.cpp.
References SharedData::gameState, SharedData::GetInstance(), Application::IsKeyPressed(), SharedData::MENU, sound, SharedData::stateCheck, and Sound::stopMusic().
Field Documentation
Camera3 SceneWin::camera private
Definition at line 96 of file SceneWin.h.
Referenced by Init(), and Render().
float SceneWin::LSPEED = 10.f private
Definition at line 87 of file SceneWin.h.
unsigned SceneWin::m_colorBuffer[NUM_GEOMETRY] private
Definition at line 80 of file SceneWin.h.
unsigned SceneWin::m_indexBuffer[NUM_GEOMETRY] private
Definition at line 78 of file SceneWin.h.
unsigned SceneWin::m_parameters[U_TOTAL] private
Definition at line 82 of file SceneWin.h.
Referenced by Init(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned SceneWin::m_programID private
Definition at line 81 of file SceneWin.h.
Referenced by Exit(), and Init().
unsigned SceneWin::m_vertexArrayID private
Definition at line 77 of file SceneWin.h.
Referenced by Exit(), and Init().
unsigned SceneWin::m_vertexBuffer[NUM_GEOMETRY] private
Definition at line 79 of file SceneWin.h.
Mesh* SceneWin::meshList[NUM_GEOMETRY] private
Definition at line 84 of file SceneWin.h.
Referenced by Init(), and Render().
MS SceneWin::modelStack private
Definition at line 86 of file SceneWin.h.
Referenced by Render(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
float SceneWin::moveSkyBoxX = 0.f private
Definition at line 89 of file SceneWin.h.
float SceneWin::moveSkyBoxZ = 91.f private
Definition at line 88 of file SceneWin.h.
MS SceneWin::projectionStack private
Definition at line 86 of file SceneWin.h.
Referenced by Init(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
Sound SceneWin::sound private
Definition at line 98 of file SceneWin.h.
Referenced by Init(), and Update().
MS SceneWin::viewStack private
Definition at line 86 of file SceneWin.h.
Referenced by Render(), RenderMesh(), RenderQuadOnScreen(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
MyGraphics/Source/SceneWin.h
MyGraphics/Source/SceneWin.cpp